### ISSUE TITLE
adm1 codes (missing FIPS, partial HASC, need ISO)

### ISSUE THREAD

**Issue by nvkelso** [nvkelso/natural-earth-vector#10]
See this thread in the forums:
http://www.naturalearthdata.com/forums/topic.php?id=471&replies=3#post-1048

**Comment by karimbahgat** [comment]
Looks like the problem with missing codes is still an issue, which is undestandable given how huge a task it is. But I have a proposal. I need accurate codes for all provinces of the world and will be going through the statoids.com pages for every country as part of another project anyway, so I thought I might as well update the natural earth adm1 codes. Before I start though, I wanted to check if it is okay that I overwrite all Natural Earth adm1 codes to the codes listed on statoids.com, which in my view is likely to be very accurate given the amount of efforts the author of that site has put in? Specifically I will update HASC ("code_hasc"), ISO1 ("iso_3166_2"), and FIPS ("fips") -- are these the correct variables I should be updating. And what specifically are the "gns_" versions of these variables ( #121 )? 

I will probably make a new Github repo which I can link to, and that way track my changes, and make it easier/more manageable to let others contribute codes for individual countries if they want to speed it up. 

Similar to #105, in order to better see the changes, I thought I could convert the original adm1 shapefile to geojson and then make my changes to the same geojson file. Then after you skim the changes if you decide to keep it you can just convert the geojson to shapefile? 

One last thing, when I use Python to try to load and then save the dbf file using "utf8" I get encoding error, but not if I use "latin". So I wonder if the file encoding is "latin" instead of "utf8" as claimed, relevant for #89 .

**Comment by nvkelso** [comment]
Does this file have more of what you need?
http://static.quattroshapes.com/ne_adm1.zip

Would be great if you could add more. Please retest your Python workflow
against it (should certainly be UTF8 encoding).

Yeah, GeoJSON is much easier to do a diff with. Suggest each property is on
it's own line to make this even easier. Just make a repo with the GeoJSON
file before and after and I'll take care of merging it back.

_n

**Comment by karimbahgat** [comment]
Hi,

Apologies for the belated response. No, from a quick scan through the quattroshapes version missing codes still seems pervasive for iso codes and occasional for hasc codes, I don't see any major differences in the codes. Since I will be going through all the statoid pages anyway I might just as well update everything. 

But should I use the github version or the quattroshapes version? Which is the newer more updated one in general / did you ever get around to moving v3 over to github? 

Thanks

**Comment by sventech** [comment]
We've been updating the ISO3166-2 data here with MIT license -- you're welcome to use it:
https://github.com/benkeen/country-region-data

The Statoids offers the data for sale, and the HASC codes do not seem to correspond to ISO codes except for Europe, USA, UK, etc.

**Comment by sventech** [comment]
Looks like this has been addressed here:
https://github.com/nvkelso/natural-earth-vector/pull/128

**Comment by nvkelso** [comment]
Agree, closing. More improvements in PR https://github.com/nvkelso/natural-earth-vector/pull/199 are in the works.

**Comment by nvkelso** [comment]
Also fixes http://www.naturalearthdata.com/corrections/admin/admin_ticket.php?track=3P4L9Z3WVQ&Refresh=40217.
