### ISSUE TITLE
Confused with ISO_A3 and SU_A3 country codes and in ne_10m_admin_0_countries

### ISSUE THREAD

**Issue by yaph** [nvkelso/natural-earth-vector#112]
So far I've used SU_A3 as identifiers thinking they are equivalent to ISO3 country codes. This is not the case for Palestine where the ISO3 code is PSE and the SU_A3 code PSX. I'm wondering what the SU_A3 code actually is based upon.

As a workaround I wanted to use the ISO_A3 property, but this has a value of -99 for Norway and France for example. Why is that?

This applies to the ne_10m_admin_0_countries v3.1.0 dataset.

**Comment by ajmas** [comment]
Seeing the same issue in current master, in ne_10m_admin_0_countries.geojson, additionally the following countries have no ISO_A3 value:

-99, Akrotiri
-99, Ashmore and Cartier Is.
-99, Baikonur
-99, Bajo Nuevo Bank (Petrel Is.)
-99, Clipperton I.
-99, Coral Sea Is.
-99, Cyprus U.N. Buffer Zone
-99, Dhekelia
-99, France
-99, Indian Ocean Ter.
-99, Kosovo
-99, N. Cyprus
-99, Norway
-99, Scarborough Reef
-99, Serranilla Bank
-99, Siachen Glacier
-99, Somaliland
-99, Spratly Is.
-99, USNB Guantanamo Bay

I am tempted to make some changes myself, but I am not sure whether the file is derived or edited directly? If it is derived, which is the master file?

**Comment by nvkelso** [comment]
You're looking for an ISO_A3 fuzzy column, which doesn't exist. You'll need to inspect each adm0 "level" file looking for the exact ISO_A3 match. For instance, the "country" of France in Natural Earth doesn't completely match with ISO's definition because of the overseas regions. But look in "map unit" and you should find the exact match. The non-ISO `*_A3` codes are special to Natural Earth, and derive from the [details](https://github.com/nvkelso/natural-earth-vector/blob/master/housekeeping/ne_admin_0_details.xls) Excel file which is exported as CSV and joined during the adm0 polygon making process.

**Comment by Sieboldianus** [comment]
For anyone, here is the updated link to [details](https://github.com/nvkelso/natural-earth-vector/blob/master/housekeeping/ne_admin_0_details.ods)
