### ISSUE TITLE
Metropolitan France should receive `FR` ISO code (like Norway)

### ISSUE THREAD

**Issue by nvkelso** [nvkelso/natural-earth-vector#12]

**Comment by nvkelso** [comment]
This was completed in 3.x series.

**Comment by woodpeck** [comment]
I downloaded ne_10m_admin_0_countries.zip today (v4.0.0) and it (still) lists -99 in the ISO_A2 column for France and Norway. I don't know if this is technically correct on some complex level and feel free to discard this report if it is intentional, but I'm pretty sure I'm not the only user for whom this comes as a surprise. The above discussion sounds like you thought abut the issue but it's not really clear to me if the outcome of the discussion was "yep, France doesn't technically have an ISO_A2 so -99 is correct", or if the outcome was "this should be fixed" (and isn't).

**Comment by nvkelso** [comment]
Hi Frederick. Yes, there is a technical difference of interpretation over what's what with ISO codes and how the "admin-0" units of the world are organized between ISO and Natural Earth. The `iso_a3_eh` column was added as a way to bridge this difference and be easier, though incorrect,
 for most downstream users (similar to `woe_id_eh`). But looks like `FRA` wasn't set yet, and you probably also want to see an `iso_a2_eh` column I take it?

In any event, this particular issue was about a different thing (setting `FR` on the map unit level), so I'll create a new issue to track the new work.
