### ISSUE TITLE
zip files have been removed

### ISSUE THREAD

**Issue by esc24** [nvkelso/natural-earth-vector#129]
Hi @nvkelso, I noticed today that https://github.com/nvkelso/natural-earth-vector/commit/4db6e25860af9d144092467afdaae71af3404651 removed all of the zip files in `natural-earth-vector/tree/master/zips`. Was this intentional? I assume that it was, but wanted to check.

**Comment by nvkelso** [comment]
Yeah, unfortunately.

Github changed their policy about large files which had prevented Natural
Earth version 3 (which has been live on naturalearthdata.com for a while
now) from being pushed to the public repo at github.com. Additionally, the
ZIP files were gunking up the repo, causing the repo's file size to be in
the 10s of GB which was causing related push errors due to Github file pack
limits.

Github continues to ignore (and actively discourage) the use case around
binary files and large files. When Natural Earth was first added to Github
there were soft limits with warnings in place, those have now turned into
hard errors that couldn't be addressed except by deleting the large files,
and removing them from the repo's history. Kinda drastic, but the only good
option. At least the repo's more manageable to work with now ;)

Removing these files, and some other changes, allowed the repo to correctly
reflect the state of the project (version 2 was quite old compared to
version 3, and people were beginning to fork and submit changes based on
the old series).

The Makefile will still generate the ZIPs and publish them to
naturalearthdata.com, but they are no longer tracked in the git repo.

If you or anyone else got in the habit of downloading the ZIPs from Github,
that workflow will now need to point directly at NaturalEarthData.com for
the same resources.

Sorry for the change up :\

**Comment by esc24** [comment]
Thanks for the prompt and clear reply.
