### ISSUE TITLE
river Kama needs a more important scale rank 10m, 50m

### ISSUE THREAD

**Issue by nvkelso** [nvkelso/natural-earth-vector#14]
The mighty river Kama deserves a place on the 50m theme. She's much bigger than the Danube, Mississipp, Rhinei or others

Between lake Onega and the White Lake/Lake Beloye in the southeast flows rivers Vytegra and Kovzha. Nowadays they form part of the Volgo-Baltic Waterway but they are still proper rivers themselves

Best regards Max S, Sweden

**Comment by MrGawsome** [comment]
This is a similar issue to #340 

After research, this seems to be part of a larger problem of some rivers that are part of the Unified Deep Water System of European Russia having higher min zoom numbers. I suggest that not only should Kama River decrease its min_zoom to 4.0, but other rivers of this Russian river system should decrease their min_zoom to 4.0 as well. I also suggest that if possible, maybe the rivers that are part of this Russian River system can be included in the 50m shapefile as well if they are missing from that file (Kama River is still on the 50m file, so that is good)? This is because this is a major and important river system, for “The Unified Deep Water System of Russia (EGS) today provides about 70% of the total traffic by inland waterways… of our country and is part of the most important international transport routes.” It connects some of the largest seas of Europe, such as the Black Sea, Caspian Sea, White Sea, and Baltic Sea, with various cities, including Moscow.

See below for sources for the Unified Deep Water System of European Russia and some of its rivers:
Russian document where the quote from the previous paragraph came from: http://rostransport.com/transportrf/pdf/33/52-53.pdf
Russian government website with a good map highlighting the Unified Deep Water System of European Russia: http://eng.morflot.ru/activities/vvt.html
Another Russian government website: http://archive.premier.gov.ru/eng/visits/ru/6044/info/1588/print/
More maps and general information about the river system: https://unece.org/fileadmin/DAM/trans/doc/2018/sc3wp3/5.8_NONIUS_Engineering.pdf
Wiki: https://en.wikipedia.org/wiki/Unified_Deep_Water_System_of_European_Russia#cite_note-RosTransportArticle-1

**Note, a separate issue will be filed with further details on what rivers of the Unified Deep Water System of European Russia should have their min_zoom levels modified to 4.0, as well as what rivers are missing from 10m_rivers_lake_centerlines_scale_rank, ne_10m_rivers_europe, and 50m_rivers_lake_centerlines_scale_rank shapefiles.

**Comment by nvkelso** [comment]
I agree Kama river should be added to the 50m theme, connecting Samara to Perm upstream from Volgograd. This means it's min_zoom also needs to change on the 10m theme to 4.0 or 4.7 per the other issue.

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/525.
