### ISSUE TITLE
50m cultural data

### ISSUE THREAD

**Issue by RamiroOliva** [nvkelso/natural-earth-vector#143]
Hi!
How I can derive 50m scale cultural data from the 10m shape file (which includes all provinces)?
Is there any open source tool to help in doing this?
Thanks.

**Comment by nvkelso** [comment]
MapShaper.org is the best tool for this. It's very easy to use as a one-off (input the 10m polygons, adjust the threshold until precision of 50m has been reached, export). 

It's more complicated to use the result to topologically build the missing 50m admin-1 regions (states, provinces) in a repeatable way. Instead of using the polygons, the 10m lines would be used instead, and then snapped to the country boundaries and coastlines. Mostly likely this would be done for ~20 countries that have large administrative subdivisions (the rest are too small to really be usable at 1:50,000,000 scale). Alternatively these other features could be shown with a point instead.

Related: https://github.com/nvkelso/natural-earth-vector/issues/120

**Comment by RamiroOliva** [comment]
Thanks, that worked quite well.
