### ISSUE TITLE
France, Japan, and Finland missing scattered ISO 3166-2 codes

### ISSUE THREAD

**Issue by migurski** [nvkelso/natural-earth-vector#191]
See most recent changes to https://github.com/openaddresses/machine/commits/master/openaddr/geodata/ne_10m_admin_1_states_provinces-54029.dbf for details.

**Comment by nvkelso** [comment]
Thanks please keep these coming!

**Comment by nvkelso** [comment]
Fixed in PR https://github.com/nvkelso/natural-earth-vector/issues/199, except for 8:

- GBR-2747 (`GB-ZET` used instead), KOR-2509 (`KR-47` used instead), POL-3147 (`PL-LD` used instead), RUS-2399 (`RU-ARK` used instead, very confusing), RUS-2354 (`RU-ALT` used instead), ATF-5918 (ISO doesn't provide ID for this feature so set to `TF-X1~` like Mike proposes with `X1~` meaning we have a custom code), TJK-5491 (`TJ-DU` used instead), UKR-321 (`UA-32` used instead, was confused with city-state versus region)
