### ISSUE TITLE
ne_10m_admin_0_map_subunits: Korea

### ISSUE THREAD

**Issue by raffam** [nvkelso/natural-earth-vector#205]
ne_10m_admin_0_map_subunits contain 2 "duplicates" for South Korea
I say duplicate because they are identical except for some _A3 code, that appears typical to NaturalEarth, GDP and population. The 2 entries seem to refer one to the main land and the other one to the insular areas.
Wouldn't be better to have different names for them? Like "South Korea (metropolitan)" and "South Korea (island" or something like that
There is also Russia, but there at least the continent is different (one is in Europe and the other one is in Asia)
This duplicates cause problems when you try to merge dataset

**Comment by nvkelso** [comment]
It's better to merge datasets via an identifier like ISO code (rather than a name), and joins for admin0 features should generally be performed against the country or map units (not subunits).

**Comment by nvkelso** [comment]
`KXI` does refer to the minor island portion of South Korea (shown in yellow):

<img width="227" alt="screen shot 2017-07-29 at 20 38 13" src="https://user-images.githubusercontent.com/853051/28750387-fabd2bee-749d-11e7-8c43-a796305cf09e.png">

Since it doesn't have a rational name by itself, and the subunits are for labeling purposes only (not joining), I'm closing this issue. But thanks for your feedback!
