### ISSUE TITLE
Add Wikidata concordances and names for more feature classes

### ISSUE THREAD

**Issue by nvkelso** [nvkelso/natural-earth-vector#224]
Following up from #214 which added the same for the 7k populated places... Let's do the same for other placetypes! Also adds names in more languages.

To start of the conversation:

- [ ] admin0 "countries" `human-verified`
- [ ] admin1 "states" - `machine-guess`
- [ ] rivers
- [ ] lakes
- [ ] playas
- [ ] physical labels (like continents, oceans, mountains, marine areas)
- ~~parks~~
- [ ] airports
- ~~ports~~
- [ ] redux on populated places with new matches and new names (21 now, not ~7) - `human-machine-guess`

**Comment by planemad** [comment]
Wonder if we can use openrefine to match with Wikidata https://github.com/wetneb/openrefine-wikidata

**Comment by ImreSamu** [comment]
@planemad : 
imho:
**openrefine**:  it can be used for admin0/admin1/airports matching, because 
*  countries/states wikidata information probably complete and good quality
*  ~ low numbers ( ideal for human matching )
* no need special scoring ( we have ISO code, IATA code )

for the 7K populated places - I have used handcrafted scoring+matching  + google sheet as a GUI

**Comment by planemad** [comment]
It worked! Matched the 177 country names to Wikidata using [openrefine](http://openrefine.org/) in under 20 mins.

Data: [Natural EarthV4 Countries: Name Wikidata Match](https://docs.google.com/spreadsheets/d/1G6Vp8UOu5F1QMRJFPR43vE0CY7AEirxCBubVa2x5Kl4/edit#gid=0)

## Process
- Export `110m_admin_0 countries` shape to a CSV
- Open CSV in [openrefine](http://openrefine.org/)
- Select `NAME_LONG`  column and `Reconcile>Start Reconciling`
- Choose to Reconcile with the Wikidata `Country` property with the ISO 3166 A3 code as fallback <br><img width="896" alt="screen shot 2017-10-31 at 3 27 45 pm" src="https://user-images.githubusercontent.com/126868/32230816-42967452-be54-11e7-9390-2658c26449d6.png">
- Wait 5 mins for matches. Only 5 failed. Took a few minutes to find the matches manually through the interface
- Export the matched ids to a new columns using the expression `cell.recon.match.id`<br><img width="693" alt="screen shot 2017-10-31 at 3 43 54 pm" src="https://user-images.githubusercontent.com/126868/32230818-42b60d94-be54-11e7-9f2b-413f13242f21.png">

Reference: [Reconcile Wikidata Tutorial](https://medium.com/@seeksanusername/reconcilier-une-liste-darchitecte-avec-wikidata-en-utilisant-openrefine-16819fbb2903)

**Comment by planemad** [comment]
## Airports

This one took a couple of hours:
- 93%+ match based on iata code and name
- ~40 were matched manually, some due to duplicate Wikidata and incorrect/outdated NE data
- 4 airports have no matches <br><img width="232" alt="screen shot 2017-11-01 at 6 39 00 pm" src="https://user-images.githubusercontent.com/126868/32288423-2d49a804-bf34-11e7-9fcc-d8e2c96182a3.png">
- This might need some human 👀 to update NE data. Some airports have ben closed, renamed have typos or are just non existent like "Munich Freight"
- Have added some additional columns for validation data validation in the sheet based on the name batch between NE and Wikidata.


Sheet: **[Airport IATA Name Wikidata match](https://docs.google.com/spreadsheets/d/1G6Vp8UOu5F1QMRJFPR43vE0CY7AEirxCBubVa2x5Kl4/edit#gid=269409115)**

**Comment by nvkelso** [comment]
Splitting Who's On First concordances off from this issue to keep it focused...

**Comment by ImreSamu** [comment]
Wikidata - to lakes ...   first candidate 
worksheet ( anybody can comment ) first version
https://docs.google.com/spreadsheets/d/1oNV4ydEXXgbeowQT2xdUMi_4crN6gdthrx6hzeigkMQ/edit?usp=sharing

**Comment by ImreSamu** [comment]
* admin_0_disputed_areas
* admin_0_map_subunits
* admin_1_states_provinces

https://docs.google.com/spreadsheets/d/1tgJnLdZOeYf_uWk8L6TXjOORJOcHBNHsVxfcBUB30Rs/edit?usp=sharing

**Comment by ImreSamu** [comment]
* `ne_10m_admin_0_countries` - 255 countries

https://docs.google.com/spreadsheets/d/1V7p2RrqIcPqjTvdT9cbzze2QcRa5H4AS-fJElY4gAnM/edit?usp=sharing

cross-checked with  @planemad 110m_admin_0 countries (177 matching )

**Comment by ImreSamu** [comment]
* ne_10m_airports

https://docs.google.com/spreadsheets/d/1hegMTz6i0poQPi2zKb4rey0uf2j_CpK-EMOgj0Xg300/edit?usp=sharing


> This might need some human eyes to update NE data.  ...

cross-checked with @planemad results.  
* I have found only ~38 differences, and after manually checking every difference,  
   *  24 was imported from the @planemad matches  
Big thank you @planemad!  :+1: 

Summary:  it was not an easy task, and the Wikidata airport data is not so perfect yet.  :( 
* [wikidata:Constraint violations report for ICAO airport code](https://www.wikidata.org/wiki/Wikidata:Database_reports/Constraint_violations/P239)
* [wikidata:Constraint violations report for IATA airport code](https://www.wikidata.org/wiki/Wikidata:Database_reports/Constraint_violations/P238)

**Comment by ImreSamu** [comment]
*  ne_10m_playas

https://docs.google.com/spreadsheets/d/1grYyD5X9pvJVcQMc2Mx78gqOf5TPNJqNOl5dnIzRpg0/edit?usp=sharing

**Comment by ImreSamu** [comment]
*  ne_10m_populated_places

some new matches 
https://docs.google.com/spreadsheets/d/1yULREfJ2DY-F1dnfRILsibbwDUjXga-NQZ_p_Z6gJ5o/edit?usp=sharing

**Comment by ImreSamu** [comment]
*  ne_10m_geography_marine_polys

https://docs.google.com/spreadsheets/d/1ANoVoJrvbxm8Hhcp4aXbYUgA7QBLKpLFNiBj9l038pc/edit?usp=sharing

**Comment by nvkelso** [comment]
Started a PR for this here https://github.com/nvkelso/natural-earth-vector/pull/249.

**Comment by nvkelso** [comment]
This has been released on the public download site: https://www.naturalearthdata.com/blog/miscellaneous/natural-earth-v4-1-0-release-notes/
