### ISSUE TITLE
Geo polygons and lakes name fix 

### ISSUE THREAD

**Issue by Maxszik** [nvkelso/natural-earth-vector#236]
`ne_10m_geography_regions_polys`, `ne_50m_geography_regions_polys`: `Neu Schawbenland` should be `Neuschwabenland` or possible `New Swabia` [link](https://en.wikipedia.org/wiki/New_Swabia).

`Psoyskoe O.` in ne_50m_lakes and `Psoyskoe Ozero` in ne_10m_lakes should be spelled `Pskovskoe O.`/`Pskovskoe Ozero`.

**Comment by MrGawsome** [comment]
For Neuschwabenland/New Swabia, I propose using Neuschwabenland as the new name, since more official sources use this name. New Swabia seems to be the English translated version of the name, but it isn’t used on some English maps, so I propose using it as an alternate name if possible. We can make these changes on the ne_10m_geography_regions_polys and ne_50m_geography_regions_polys shapefiles for ne_id 1159104649. See below:

Norgegian English version document, which cites the name “Neuschwabenland” and shows a map of “Dronning Maud Land,” which is the area that Neuschwabenland is a part of:
https://www.regjeringen.no/contentassets/cef2a67e958849689aa7e89341159f29/en-gb/pdfs/stm201420150032000engpdfs.pdf
History.com article using both names: https://www.history.com/news/hitler-nazi-secret-expedition-antarctica-whale-oil
Map showing the “Neuschwabenland” name:
https://lh3.googleusercontent.com/proxy/gPQQkkbSQ4DcPp47-jv6yjCmIho5PWu7GPn1jY3tq-ppYKuMa9a2H7legYo1iFzsUN54iEGIVjIireNgrCOMSvtMCG5Adl7MVKwUTF9fnn3GRlv9pB10pnIVqq3ktsIAppRsSBVCVe-zgXM
This map was taken from: https://posterwissen.de/maps/map.php?Antarctica_(New_Swabia/Queen_Maud_Land)&id=259&ln=en
New Zealand map showing a “New Schwabenland” name, which is similar to Neuschwabenland:
https://data.gns.cri.nz/ata_geomap/index.html?map=Antarctic
New Swabia/Neuschwabenland wiki: https://en.wikipedia.org/wiki/New_Swabia
Queen Maud Land wiki, which New Swabia is a part of:
https://en.wikipedia.org/wiki/Queen_Maud_Land
Another wiki about general claims and history of them in Antarctica: https://en.wikipedia.org/wiki/Territorial_claims_in_Antarctica#cite_ref-1

For Psoyskoe Ozero, I propose changing the name to Lake Pskov and then using the name Pskovskoe Ozero as an alternate name since Lake Peipus, the adjacent lake, uses the English name as the primary name and then the Russian name as the alternate name. We can do this on both the ne_10m_lakes and ne_50m_lakes shapefiles for ne_id 1159113451. “Pskovskoe Ozero” is Russian for “Pskov Lake,” so either name is suitable here. See the below sources for name confirmations for Lake Pskov:

World Lakes, which mentions Lake Pskov in the description: http://www.worldlakes.org/lakedetails.asp?lakeid=8767
UN document with a map on page 1: http://www.unesco.org/new/fileadmin/MULTIMEDIA/HQ/SC/pdf/wwap_Lake%20Peipsi%20%20Chudskoe_case%20studies1_EN.pdf
Britannica encyclopedia, which mentions Lake Pskov: https://www.britannica.com/place/Lake-Peipus
Russian article which mentions Lake Pskov: http://www.outdoors.ru/abc/abc2139.php
Wiki which explains that Lake Peipsi is broken into 3 parts, with Lake Pskov being one of these parts: https://en.wikipedia.org/wiki/Lake_Peipus

**Comment by nvkelso** [comment]
I see **ne_id** = `1159104649` with **name** = `New Schawbenland` in Antarctica. Are we talking about the same place? If so the **wikidataid** (which is missing now) should be `Q252609` and we'd pick up name localizations.

For the default **name** I'd use `New Swabia` as all the other names in that area are already using English so it's more consistent. Since the common local name is `Neuschwabenland` I'm fine storing that as a **name_alt**. (The name localizations from Wikidata for German and Norwegian would show `Neuschwabenland`.)

NOTE: The 50m theme is build with a Makefile command so no need to edit that separately:

> make derived_physical_labels

- https://github.com/nvkelso/natural-earth-vector/blob/master/Makefile#L654-L668

**Comment by nvkelso** [comment]
For **ne_id** = `1159113451` with **name** = `Pskoyskoye Ozero` in the 10m and 50m themes I agree with @MrGawsome's proposal. The lake is mostly in Russia so w can use the English translation of Russian as the default (and as done in earlier versions of NE but with the funky name), but let's also set **name_alt** to both country's romanized values.

- **name** = `Lake Pskov`
- **name_abbr** = `L. Pskov`
- **name_alt** = `Pihkva järv|Pskovskoe Ozero`
- **label** = `Pskov`

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/525.
