### ISSUE TITLE
Shouldn't Norway's ISO_N3 be 578?

### ISSUE THREAD

**Issue by Fil** [nvkelso/natural-earth-vector#268]
It is currently -99 on line 353 (Sovereign country), and the correct code 578 is on line 356 (geo unit exact WOE match as country).

For all I know it seems to have changed with https://github.com/nvkelso/natural-earth-vector/commit/4db6e25860af9d144092467afdaae71af3404651 — though the commit log doesn't mention it.

(Spotted when trying to update [world-atlas](https://github.com/topojson/world-atlas))

**Comment by nvkelso** [comment]
Look in the countries file instead.

**Comment by Fil** [comment]
To be clear, in v2.0.0 (http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/cultural/ne_110m_admin_0_countries.zip?version=2.0.0) we have 578 

![capture d ecran 2018-08-15 a 12 23 57](https://user-images.githubusercontent.com/7001/44144244-f5cdea18-a086-11e8-8fa9-18897e1441b6.png)

In v4.0.0 (http://naciscdn.org/naturalearth/110m/cultural/ne_110m_admin_0_countries.zip) it has become -99

![capture d ecran 2018-08-15 a 12 26 37](https://user-images.githubusercontent.com/7001/44144258-031fae5e-a087-11e8-8bfa-7a6768786337.png)

(I thought I had located the source issue in that upstream file commit but the whole repo is a bit opaque, I might have looked in the wrong place.)

**Comment by renedlog** [comment]
Any updates on this problem...?
its still a problem in 4.1.0

see also:
https://github.com/nvkelso/natural-earth-vector/issues/284
https://github.com/nvkelso/natural-earth-vector/issues/252

**Comment by nvkelso** [comment]
Natural Earth's practice is to be strict on the ISO code mappings. The "strict" mapping are already available in the other map unit admin detail themes (not country).

Because Natural Earth has a more fidelity than ISO, and tracks countries that ISO doesn't, Natural Earth maintains it's own set of 3-character codes for each admin-0 related feature. The original intent was consumers of Natural Earth would maintain their own data code mappings between their "worldview" and this data. But most people use the ISO 2-char and 3-char shortcuts included in the data properties.

The ISO_A3_EH ("eh" as in okay but not great) column addressed the "fuzzy" or "loose" use case (while introducing possible errors in your visualization &/or analysis depending on how your data is setup – you should interview your data). But it looks like you are working with 2-character ISO codes and not 3-character ISO codes. That's a fairly common use case, and I can see adding a new ISO_A2_EH column for this.

The following 2 commits (my branch not mainline) address this:

- https://github.com/nvkelso/natural-earth-vector/commit/cd16b951daf68025ab7f515764fdc690cdd1167c
- https://github.com/nvkelso/natural-earth-vector/commit/709ffdf7e55f73a0d81dd1adcb4a1032a38e3730

Add `iso_a2_eh` and `iso_n3_eh` columns, addressing the FR and NO cases (and others):

<img width="812" alt="Screen Shot 2021-01-06 at 09 16 35" src="https://user-images.githubusercontent.com/853051/103799520-0c35b300-5000-11eb-9a61-78bd270e721d.png">

<img width="778" alt="Screen Shot 2021-01-06 at 09 16 53" src="https://user-images.githubusercontent.com/853051/103799509-08a22c00-5000-11eb-9990-550b7aa8371c.png">

Preview GeoJSON:

- https://github.com/nvkelso/natural-earth-vector/blob/v5-prequel/geojson/ne_10m_admin_0_countries.geojson
- https://github.com/nvkelso/natural-earth-vector/blob/v5-prequel/geojson/ne_50m_admin_0_countries.geojson
- https://github.com/nvkelso/natural-earth-vector/blob/v5-prequel/geojson/ne_110m_admin_0_countries.geojson

**Comment by mapadofu** [comment]
@nvkelso 

If I'm following this thread correctly, natural-earth-vector won't set the value for France's 'ISO_A3' field to be 'FRA' (despite the fact that that is the ISO-alpha3 code for France...)  and that I have to use 'ISO_A3_EH' to get France's ISO-alpha3 code.

Am I reading this correctly?

**Comment by nvkelso** [comment]
@mapadofu Yes, that is correct. It's not an exact match.

![image](https://user-images.githubusercontent.com/853051/121845258-08d2e180-cc9a-11eb-9533-4e849cf975bf.png)

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/446.

**Comment by bbolker** [comment]
Since this is still a frequently asked question by people who are new to the nuances, would you be willing to give a *slightly* more in-depth explanation of what the issue is (beyond "It's not an exact match" from [this comment](https://github.com/nvkelso/natural-earth-vector/issues/268#issuecomment-860387631))? Where is the ambiguity/imprecision with associating France ISO-A2 with "FR" or Norway with "NO"?

**Comment by MrGranddy** [comment]
> Since this is still a frequently asked question by people who are new to the nuances, would you be willing to give a _slightly_ more in-depth explanation of what the issue is (beyond "It's not an exact match" from [this comment](https://github.com/nvkelso/natural-earth-vector/issues/268#issuecomment-860387631))? Where is the ambiguity/imprecision with associating France ISO-A2 with "FR" or Norway with "NO"?

Standards exist for a reason. If a field is supposed to follow a specific standard, like the ISO Alpha-2 codes, then it should adhere to that without exceptions. Imagine using these ISO abbreviations as unique keys to query data from another source that also uses the "true" ISO keys. If the keys don't match, even due to minor deviations, it creates a significant problem. Should it be my responsibility to double-check every single piece of information in a repository when it clearly states something is something?

Even if such errors occur accidentally, there's no reason why they shouldn't be corrected. Standards are there to eliminate ambiguities and ensure consistency across different systems. Allowing nuances or exceptions in strict standards defeats their very purpose, as we can't feasibly verify every potential discrepancy in every technology we use. So yes, maintaining strict adherence to standards is crucial, and any deviations should be fixed to avoid unnecessary complications.

**Comment by bbolker** [comment]
To be clear, I'm **not** saying that you should do anything different! As an outsider (who doesn't even do this stuff, just trying to answer someone's question on Stack Overflow), I'm just trying to understand where the ambiguity actually arises. That is, if I look on [Wikipedia](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#FR) (obviously *not* a canonical reference), I see "FR" defined for France (and similarly [FRA for A3](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3)).

When I use R's `rnaturalearth` package (which is downstream of Natural Earth, so maybe something else is happening?), I see that `iso_a2` and `iso_a3` are undefined for France (code below). I see that you say above that

> Because Natural Earth has a more fidelity than ISO, and tracks countries that ISO doesn't, Natural Earth maintains it's own set of 3-character codes for each admin-0 related feature.

I'm truly not trying to be difficult, I'm just trying to understand the ultimate source of this ambiguity. For example, is there some other region that could be defined as "FR", or "FRA"? Or is "France" not uniquely defined?

In the [question I was answering](https://stackoverflow.com/questions/78803961/countries-fr-and-no-seem-to-be-ignored-by-rnaturalearth/78804926#78804926) someone was trying to match the code "FR" to the `iso_a2` field &mdash; which seems to be an example of "true" ISO_A2? (i.e., they're *not* trying to do a fuzzy match ...)

Thanks for your patience.


```r
library(rnaturalearth)
fr <- subset(ne_countries(), iso_a2_eh=="FR", select = c(name, iso_a2, iso_a2_eh, iso_a3, iso_a3_eh))
> fr
Simple feature collection with 1 feature and 5 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: -54.52475 ymin: 2.053389 xmax: 9.560016 ymax: 51.14851
Geodetic CRS:  WGS 84
     name iso_a2 iso_a2_eh iso_a3 iso_a3_eh                       geometry
44 France    -99        FR    -99       FRA MULTIPOLYGON (((-51.6578 4....
```

**Comment by nvkelso** [comment]
Hey @bbolker, great question and happy to provide more explanation.

For a downstream data viz library like `rnaturalearth`, they could consider adding middleware logic to map any data table's `ISO` code's to Natural Earth's `ISO_EH` codes by default, or to map first to the strict interpretation and then to the "fuzzy" ("eh" interpretation) fallback.

So the backstory is complicated. There are features in Natural Earth with an exact ISO match for France & etc, but they may be at the next admin level down from "countries" (eg "map units"). Which I recognize is awkward when trying to do data viz and you want to join against just a single shapefile. Generally Natural Earth started out as a map display dataset and then grew data visualization abilities, so for history and backwards/forwards compatibility we have this awkwardness.

Natural Earth chooses to be pedantic because we need to interoperate with more than just ISO and some of those other "standards" have different inconsistencies, so Natural Earth tries to be a flexible superset. Additionally, Natural Earth tracks population and GDP figures per admin unit at all levels, and to not "double count" or "under count" those we need to be pedantic for our own internal workflow data joins.

The problem also arises because ISO only has 1 "admin0" level while Natural Earth has 4 "admin0" levels, and Natural Earth chooses to track countries that ISO chooses to ignore or not recognize. Additionally, ISO for various historical "good reasons" tracks several overseas territories as separate "countries" (while also providing subdivision codes for them), but doesn't do this on a consistent basis between countries (like it doesn't do the same thing with United States, Alaska, and Hawaii). 

So are you talking about FR for all of France the country including it's overseas integral regions? Or about the larger France which also includes some territories? Or about just metropolitan France in Europe? Or just the part of France that's in the continent of Europe ignoring islands in the Mediterranean? Natural Earth tracks all these parts, while ISO is actually confusing and ambiguous about this. Sometimes their ambiguity is strategic, too! Some of these smaller "parts" actually have sizable populations on their own. So if you're doing detail oriented statistics, you need to interview your data and Natural Earth and find the right match. 

Generally when I'm doing my own personal data viz with Natural Earth, I add a new column to my thematic data table to include NE_A3 codes (admittedly with the ISO_A2 codes as a starting point), double check the appropriateness, modify to taste, and then proceed with the data join against the NE_A3 column in the NE countries shapefile.

If you're fine with broad stroke view and aren't concerned about the risk of a bad match (eg because less ideal matches have low consequences), that's what ISO_A2_EH is for.

**Comment by bbolker** [comment]
Thanks, that makes perfect sense. The only thing that's surprising isn't that there aren't many *more* countries without strict ISO_A[23] mappings, as I'd expect that this kind of issue would arise all the time - at the very least for any former colonial power ... As an example from the distant past, this is what you get if you ask for a map of the "UK" with an ancient R mapping package (with data going back to the 1990s ...)

```r
library(mapdata)
map("worldHires", "UK", bg = "gray", col="red", fill = TRUE)
```
![world](https://github.com/user-attachments/assets/4094ab0d-57e2-4e70-ba7a-b5b9c5852abd)

in addition to Great Britain (and possibly Channel Islands, I can't tell) it includes various overseas possessions such as South Georgia, completely messing up the scale/bounding box if all you wanted was GB ...

**Comment by nvkelso** [comment]
That's a gem, thanks for sharing :)
