### ISSUE TITLE
Incorrect coding of Kazakhstan in sovereignty dataset

### ISSUE THREAD

**Issue by atlight** [nvkelso/natural-earth-vector#313]
In `ne_50m_admin_0_sovereignty` the entire territory of Kazakhstan is incorrectly coded as the Baykonur Cosmodrome.

**Comment by nvkelso** [comment]
Agree this is a problem. It appears this is caused by the lease area and the sov being at the same level in the src table with the same sov values ('KAZ') where normally it would be `KA1` in keeping with the complexity. In the case of Cuba the lease area is sequentially in the row after the sov so it just works. 

Two actions:

- Move the lease row below the sov row so order of operations wins in join.
- Switch to `KA1` for the sov code on the sov and the lease, so the join is deterministic.
- Switch `CUB` to `CU1` for the same reasons.

![image](https://user-images.githubusercontent.com/853051/107869516-ee9c0a80-6e43-11eb-87a0-cb3d4298a0cc.png)

**Comment by nvkelso** [comment]
Fixed via 3739a74e16ed39f707aeae9e8443f2a44b789ba3 in for both Kazakhstan and Cuba. Was problem in all the sov 10m, 50m, 110m scalesets. Also fixed in admin-1.

![image](https://user-images.githubusercontent.com/853051/107870010-9405ad00-6e49-11eb-9993-d0018aade3a6.png)

![image](https://user-images.githubusercontent.com/853051/107870016-9ff16f00-6e49-11eb-9ddc-7730d9f3bfbb.png)

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/446.
