### ISSUE TITLE
Duplicate names for different polygons in `geography_marine_polys.geojson`

### ISSUE THREAD

**Issue by jbusecke** [nvkelso/natural-earth-vector#319]
Hi I recently implemented marine areas as part of the [regionmask package](https://github.com/mathause/regionmask/pull/91). 

I then noticed an abnormality when trying to combine the smaller regions into large scale ocean basins (see discussion [here](https://github.com/mathause/regionmask/issues/90)). Both the "Mediterranean Sea" and the "Ross Sea" are split into two distinct regions with the same name.

In the Case of the Mediterranean Sea I think this should be renamed in Western and Eastern Mediterranean (or Eastern and Western basin as in [here](https://github.com/MPAS-Dev/geometric_features/tree/master/geometric_data/ocean/region)) since the basins are distinct:

![Screen Shot 2020-03-20 at 4 55 01 PM](https://user-images.githubusercontent.com/14314623/77206006-6a72c300-6acc-11ea-8a45-3fcc4128dccb.jpg)
![Screen Shot 2020-03-20 at 4 55 11 PM](https://user-images.githubusercontent.com/14314623/77206012-6d6db380-6acc-11ea-933f-9355828c7cfd.jpg)

For the Ross Sea it seems like It was just sliced at the dateline? Can this be reconnected in the source file?

![Screen Shot 2020-03-20 at 4 56 26 PM](https://user-images.githubusercontent.com/14314623/77206068-870efb00-6acc-11ea-91c7-6a40e5698de6.jpg)

I would be happy to submit a PR with changes if someone could point me in the right direction. I have been mostly looking at the [geojson files](https://github.com/nvkelso/natural-earth-vector/blob/master/geojson/ne_50m_geography_marine_polys.geojson).

**Comment by MrGawsome** [comment]
Although naming the different areas of the Mediterranean Sea and Ross Sea makes sense, after some discussion, I propose merging the different parts of the Mediterranean Sea (ne_id 1159115321 and 1159116285) and Ross Sea (ne_id 1159115615 and 1159115549) together and still keep the names “Mediterranean Sea” and “Ross Sea.” Some mappers use these NE marine polygons for labels, so using the names “Eastern Mediterranean” and “Western Mediterranean” isn’t preferred and these names aren’t used on too many maps from some online research I’ve done. The use of the name “Mediterranean Sea” is more common, with some maps using 2 duplicate labels to map the eastern and western parts of the sea rather than naming them Eastern Mediterranean and Western Mediterranean. If we don’t merge these polygons, I propose keeping the NE data as is rather than changing the sea names. We’d merge the different parts of the Mediterranean Sea and Ross Sea on the geography_marine_polys shapefiles for all scales: 10m, 50m, and 110m.

Additionally, we’d need to create polygons for the geography_regions shapefiles for the Mediterranean Sea and Ross Sea with all scales (10m, 50m, and 110m).

See the below sources for more information:
Mediterranean Sea:
UN org where even though the Eastern and Western regions of the Mediterranean are discussed, on the maps they aren’t labeled this way, suggesting that only the name “Mediterranean Sea” should be used: https://www.medqsr.org/mediterranean-marine-and-coastal-environment
Another UN map: https://www.un.org/Depts/Cartographic/map/profile/ece.pdf
2 maps, 1 from the Library of Congress (LoC) and another from Nations Online, where instead of labeling the sea as “Western Mediterranean” and “Eastern Mediterranean,” 2 labels of “Mediterranean Sea” are used, similar to the current NE data. See below:
https://www.loc.gov/resource/g5672m.ct001013/?r=-0.036,-0.12,1.111,0.656,0
https://www.nationsonline.org/oneworld/map/Mediterranean-Region-Map.htm
UK national archives maps: https://www.nationalarchives.gov.uk/cabinetpapers/documents/maps-in-time.pdf
Wiki: https://en.wikipedia.org/wiki/Mediterranean_Sea

Ross Sea:
NASA: https://blogs.nasa.gov/icebridge/2014/11/19/east-and-west-the-geography-of-antarctica/
Britannica Encyclopedia: https://www.britannica.com/place/Ross-Sea
Protected Planet: https://www.protectedplanet.net/555624810
Wiki: https://en.wikipedia.org/wiki/Ross_Sea

**Comment by nvkelso** [comment]
I agree with merging the different parts of the `Mediterranean Sea` (**ne_id** = `1159115321` and `1159116285`) and `Ross Sea` (**ne_id** = `1159115615` and `1159115549`) together and still keep the names “Mediterranean Sea” and “Ross Sea.”

> Additionally, we’d need to create polygons for the geography_regions shapefiles for the Mediterranean Sea and Ross Sea with all scales (10m, 50m, and 110m).

We can skip this step. It's marginally useful for the Mediterranean Sea to encompass the an even larger shape including all the little seas and bays) but introduces more complexity / confusion. For Ross Sea it's not necessary at all since the marine label area already covers 100% of the area.

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/525.

**Comment by mathause** [comment]
thanks!
