### ISSUE TITLE
Populated places: Update spellings for major cities in Bangladesh

### ISSUE THREAD

**Issue by elliotap** [nvkelso/natural-earth-vector#329]
In 2018, Bangladesh's National Implementation Committee for Administrative Reorganizations-Reforms changed the English-language spelling of 5 districts to align more closely with their Bangla pronunciation.

Pursuant, three cities should receive updates to their name field:

For 10m & 50m populated places "Chittagong" should be changed to "Chattogram"
For 10m populated places "Jessore" should be changed to "Jashore" and "Barisal" should be changed to "Barishal"

References:
https://bangladesh.gov.bd/site/view/district-list/District-List  
https://www.dhakatribune.com/bangladesh/2018/04/02/english-spellings-chittagong-comilla-barisal-jessore-bogra-changed  
https://bdnews24.com/bangladesh/2018/04/02/bangladesh-changes-english-spellings-of-five-districts

**Comment by mizmay** [comment]
This change makes sense to me, but is not backed by the name_en value in Wikidata.

See output of Wikidata check here: https://github.com/mizmay/natural-earth-vector/blob/master/10m_cultural/ne_names_issues_compare_wikidata.csv

Proposal: Assign the old name to NAMEPAR and NAMEALT (since it is still in use), assign the new name to NAME and NAMEASCII. Localizations (including name_en) still governed by Wikidata values.

NAME: Chattogram
NAMEASCII: Chattogram
NAMEPAR: Chittagong
NAMEALT: Chittagong

NAME: Jashore
NAMEASCII: Jashore
NAMEPAR: Jessore
NAMEALT: Jessore

NAME: Barishal
NAMEASCII: Barishal
NAMEALT: Barisal
NAMEPAR: Barisal

But open to other suggestions.

**Comment by nvkelso** [comment]
Only the 10m theme should be updated, the 50m theme is auto generated:

> make derived_populated_places

If the alternate name is in NAMEPAR, you shouldn't duplicate it into NAMEALT too. So please don't update any of the NAMEALTS above.

Other proposals LGTM.

**Comment by nvkelso** [comment]
Fixed via #508 and https://github.com/nvkelso/natural-earth-vector/commit/54a661943db3e228e28d0ce756fc173aff87c0f5 to reapply #5.
