### ISSUE TITLE
The Taiwan is a part of China. Please fix the data . Appreciate you !

### ISSUE THREAD

**Issue by ghost** [nvkelso/natural-earth-vector#331]
I find the issue is on 
![image](https://user-images.githubusercontent.com/16850883/81173164-30a14180-8fd2-11ea-9a30-77305ec3f9bd.png)
![image](https://user-images.githubusercontent.com/16850883/81173860-4d8a4480-8fd3-11ea-9d04-d3ba0b5357af.png)

https://observablehq.com/@d3/world-choropleth?collection=@d3%2Fd3-geo

and I try to post on https://talk.observablehq.com/t/please-change-world-map/3225/14 

https://github.com/topojson/world-atlas

**The color of taiwan should be the same as China.**
 **The taiwan is a part of China.**
 Please be sure fix the word map .

I'm not good at coding, it's hard to me , but really really please help me to fix it. I can't use observablehq map . 

 **Really Appreciate you !**

**Comment by curran** [comment]
An interesting read https://en.wikipedia.org/wiki/Political_status_of_Taiwan

**Comment by mbloch** [comment]
Politics aside, it is a simple fact that data about Taiwan is often reported separately from mainland China. Demographic data about China, like in the above map, frequently does not include data from Taiwan. In such cases, it would be misleading to show Taiwan together with mainland China.

This seems to me to be a sufficient reason for keeping Taiwan separate in Natural Earth. If it makes sense for a particular map to show China and Taiwan together, then the map maker still has that option.

Surely this is also why Natural Earth keeps the U.S. territories of Puerto Rico, Guam, American Samoa, and the U.S. Virgin Islands separate from the 50 states in the "countries" dataset.

**Comment by nvkelso** [comment]
Starting in the v5.0 series, there are additional "point-of-view" (POV or worldview) versions of the countries theme available, including one for China which depicts Taiwan as an integral part of China (eg a province) instead of a separate sovereign country. Other disputed areas (not along China's direct sovereign frontier) around the world are also available to match the Chinese POV. 

There is also an optional new `ne_10m_admin_0_boundary_lines_disputed_areas_chn` lines theme (shown in blue stroke in screenshot below) that shows the so-called `9-dashed line` for the Chinese maritime claim.

It's important to note: The default countries theme will continue to show Taiwan as a separate sovereign country as that's the defacto situation on the ground, and  as @mbloch notes most international statistics are categorized as such.

![image](https://user-images.githubusercontent.com/853051/107887294-e54d8500-6eb9-11eb-9025-8a2f87e483df.png)

**Comment by mrUizz** [comment]
We will work hard to change this point of view peacefully, because Taiwan has been a part of China since ancient times. This is a point that people who oppose war should recognize.

**Comment by mrUizz** [comment]
As a map maker, for the controversial areas, I think you should understand the history between them instead of relying on big data analysis. We are not robots.

**Comment by nvkelso** [comment]
Added point of view options via https://github.com/nvkelso/natural-earth-vector/pull/446 which allow data driven way to match this expectation... but to be clear it is still not the default configuration.
