### ISSUE TITLE
10/50/110m lakes: Request for updated Aral Sea geometry

### ISSUE THREAD

**Issue by elliotap** [nvkelso/natural-earth-vector#337]
The Aral Sea has been disappearing, although efforts to restore it are being taken. Depending on when it is observed, the water level varies. The geometry for the eastern lobe in the natural earth data not longer matches the water level.

The following sources show/describe changes in the water level:
https://en.wikipedia.org/wiki/Aral_Sea
https://earthobservatory.nasa.gov/world-of-change/AralSea
https://modis.gsfc.nasa.gov/gallery/individual.php?db_date=2019-10-11

Requesting that the geometry for the Aral Sea polygons be investigated and modified to more current water levels.

**Comment by MrGawsome** [comment]
After much research, I propose to shrink the Aral Sea following recent aerial imagery and then break it up into 5 parts with new names as shown in the below image. I would edit Aral Sea on the 10m, 50m, and 110m shapefiles, and I’d have less detail on the 50m and 110m files.

![Aral_Sea](https://user-images.githubusercontent.com/78829897/110881791-c9a98480-8295-11eb-96ce-6566f0ae7195.png)

(A) This is referred to as the eastern part of the South Aral Sea, which is also known as the Aralkum Desert. Maybe this desert name can be added as an alternate name? I propose this lake should be removed from the ne_10m_lakes shapefile and added to the ne_10m_playas shapefile since recent imagery suggests it is dried out, at least most of the time. I propose using Wikidata Q276776 (https://www.wikidata.org/wiki/Q276776).

Sources suggesting Aral Sea’s shrinking, splitting up the lake into separate lakes, and adding the South Aral Sea and Aralkum Desert names. See the below sources:
See the gif under “Manmade Devestation”: https://eurasianet.org/northern-arals-promise-stunted-by-dam-height-international-disputes
Recent 2020 images, and the suggestion of the name “Aralkum Desert”: https://earthobservatory.nasa.gov/images/147735/aral-sea-in-winter
More 2020 imagery: https://earthobservatory.nasa.gov/images/146487/a-dusty-day-over-the-aral-sea
Wiki, which suggests separate lake names and areas of the Aral Sea: https://en.wikipedia.org/wiki/Aral_Sea#cite_note-sciam-5
Different lakes and regions of the Aral Sea (See bottom of the page above “Foresight”): https://sometimes-interesting.com/2014/11/23/the-disappearing-aral-sea/
Aralkum desert wiki: https://en.wikipedia.org/wiki/Aralkum_Desert

(B) The majority of sources seem to call this lake South Aral Sea. I propose using Wikidata Q276776 (https://www.wikidata.org/wiki/Q276776). However, sometimes this lake is named Southern Aral Sea, Large Aral Sea, or Big Aral Sea. Should these names be added as alternate names? See the sources below as well as the alternate sources before (D).

South Aral Sea name sources:
World Meteorological Organization: https://public.wmo.int/en/resources/bulletin/future-of-aral-sea-lies-transboundary-co%E2%80%93operation
Water foundation: https://www.wearewater.org/en/the-aral-sea-the-difficult-return-of-water_322871
NASA: https://earthobservatory.nasa.gov/images/147735/aral-sea-in-winter
NASA: https://earthobservatory.nasa.gov/images/146487/a-dusty-day-over-the-aral-sea
Wiki: https://en.wikipedia.org/wiki/South_Aral_Sea
OSM: https://www.openstreetmap.org/relation/5901404

(C) The majority of sources seem to call this lake North Aral Sea. I propose using Wikidata Q3358037 (https://www.wikidata.org/wiki/Q3358037). However, sometimes this lake is named Northern Aral Sea or Small Aral Sea. Should these names be added as alternate names? See the below sources suggesting all of these names, especially the name North Aral Sea:

North Aral Sea name sources:
Kazakhstan gov website: https://www.kazmab.kz/index.php/en/biosphere-reserves/2016-01-25-13-17-07/barsakelmes/description
UNESCO map, which is also featured on the KZ website above: http://www.unesco.org/new/fileadmin/MULTIMEDIA/HQ/SC/images/Map_Barsakelmes.jpg
NASA: https://earthobservatory.nasa.gov/images/147735/aral-sea-in-winter
NASA: https://earthobservatory.nasa.gov/images/146487/a-dusty-day-over-the-aral-sea
Wiki: https://en.wikipedia.org/wiki/North_Aral_Sea
OSM: https://www.openstreetmap.org/relation/8728779

Alternate names for North and South Aral Sea. Alternate names are Small Aral Sea, Northern Aral Sea, Southern Aral Sea, Large Aral Sea, or Big Aral Sea. See the below sources:
The map in the middle of the article: https://eurasianet.org/northern-arals-promise-stunted-by-dam-height-international-disputes
Central Asia org: http://ec-ifas.waterunites-ca.org/main/189-an-expedition-of-scientists-and-journalists-was-conducted-to-the-northern-part-of-the-aral-sea.html
See pdf page 18 and translate the names: https://www.zin.ru/labs/brackish/presentations/Past_present_and_future_of_the_Aral_Sea_and_Aral_Sea_Region.pdf
Science Magazine: https://science.sciencemag.org/content/370/6522/1283.1

(D) The majority of sources seem to call this lake Barsakelmes Lake. I propose using Wikidata Q28750379 (https://www.wikidata.org/wiki/Q28750379). However, OSM and a Russian source have the Russian names of “Тущыбас” and “залив Тще-Бас,“ which translates to “Tushchybas” and “Tsche-Bass Bay” respectively. A regional organization refers to the lake as “Shche-bas Bay” as well. Should these names be added as alternate names? See the below sources suggesting all of these names, especially the name Barsakelmes Lake:

Barsakelmes Lake name sources are below. I can’t find a good official source, but various miscellaneous sources cite this name. See below:
Abandoned history website (see bottom of article): https://sometimes-interesting.com/2014/11/23/the-disappearing-aral-sea/
Central Asia Travel: https://www.youtube.com/watch?v=oNJuhy0TmCc&ab_channel=CentralAsiaTravel
Wiki: https://en.wikipedia.org/wiki/Barsakelmes_Lake
Not a source, but it does show that other companies/orgs use “Barsakelmes Lake”: https://www.google.com/maps/@46.2134481,59.7070654,92141m/data=!3m1!1e3

Alternate name sources for “Tushchybas,” “Tsche-Bass Bay,” or “Shche-bas Bay”: 
A Central Asia regional organization refers to the lake as “Shche-bas Bay”:
http://ec-ifas.waterunites-ca.org/main/189-an-expedition-of-scientists-and-journalists-was-conducted-to-the-northern-part-of-the-aral-sea.html
“Tushchybas” in OSM: https://www.openstreetmap.org/way/82650612
“Tsche-Bass Bay” on page 18 of a Russian doc: https://www.zin.ru/labs/brackish/presentations/Past_present_and_future_of_the_Aral_Sea_and_Aral_Sea_Region.pdf

(E) I suggest to leave this lake as unnamed. I can’t seem to find any good source suggesting a name for this lake. It seems to be part of the Barsakelmes Biosphere Reserve. Only OSM has some names for the lake, which I can’t verify elsewhere (see below). See below for sources that don’t label the lake and show that it is part of this reserve:
OSM names: https://www.openstreetmap.org/relation/3334885
Kazakhstan gov website: https://www.kazmab.kz/index.php/en/biosphere-reserves/2016-01-25-13-17-07/barsakelmes/description
UNESCO map, which is also featured on the KZ website above: http://www.unesco.org/new/fileadmin/MULTIMEDIA/HQ/SC/images/Map_Barsakelmes.jpg

**Comment by nvkelso** [comment]
Thank you for the extensive research. I agree with the changing the shapes as you propose in the 10m theme. You will also need to make changes to the 50m and 110m themes.

Summary of your changes proposed above, which I agree with:

- A: **name** = `Aralkum Desert` as a **playa** (not a _lake_ anymore). **name_alt** = `South Aral Sea`. **wikidataid** = `Q276776`
- B: **name** = `South Aral Sea` as a **lake**. **name_alt** = `Southern Aral Sea|Large Aral Sea|Big Aral Sea`. **wikidataid** = `Q276776 `
- C: **name** = `North Aral Sea` as a **lake**. **name_alt** = `Northern Aral Sea|Small Aral Sea`. **wikidataid** = `Q3358037` 
- D:  **name** = `Barsakelmes Lake` as a **lake**. **name_alt** = `Tushchybas|Tsche-Bass Bay|Shche-bas Bay`. **wikidataid** = `Q28750379`
- E:  **name** = `` (NULL) as a **lake**. With no name alts or wikidataid.

I think the convention in the 10m file is to drop the Lake and Sea, but confirm and adjust the proposal above.

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/525.
