### ISSUE TITLE
10m rivers lake centerlines scale rank: Request for update to min zoom for Sheksna

### ISSUE THREAD

**Issue by elliotap** [nvkelso/natural-earth-vector#340]
Requesting a change to the min zoom value for the Sheksna River (id 1159109461) from 7.1 to 4.0 to more closely align with the nearby Sukhona, because although relatively short, the Sheksna River & reservoir are prominent features in the landscape here.

https://en.wikipedia.org/wiki/Sheksna_River

**Comment by Caucasus-and-Mercury** [comment]
I second that. Sheksna is navigable and part of a major waterway, the Volga-Baltic.

**Comment by MrGawsome** [comment]
After research, this seems to be part of a larger problem of some rivers that are part of the Unified Deep Water System of European Russia having higher min zoom numbers. I suggest that not only should Sheksna River decrease its min_zoom to 4.0, but other rivers of this Russian river system should decrease their min_zoom to 4.0 as well. I also suggest that if possible, maybe the rivers that are part of this Russian River system can be included in the 50m shapefile as well if they are missing from that file (such as Sheksna River)? This is because this is a major and important river system, for “The Unified Deep Water System of Russia (EGS) today provides about 70% of the total traffic by inland waterways… of our country and is part of the most important international transport routes.” It connects some of the largest seas of Europe, such as the Black Sea, Caspian Sea, White Sea, and Baltic Sea, with various cities, including Moscow.

See below for sources for the Unified Deep Water System of European Russia and some of its rivers:
Russian document where the quote from the previous paragraph came from: http://rostransport.com/transportrf/pdf/33/52-53.pdf
Russian government website with a good map highlighting the Unified Deep Water System of European Russia: http://eng.morflot.ru/activities/vvt.html
Another Russian government website: http://archive.premier.gov.ru/eng/visits/ru/6044/info/1588/print/
More maps and general information about the river system: https://unece.org/fileadmin/DAM/trans/doc/2018/sc3wp3/5.8_NONIUS_Engineering.pdf
Wiki: https://en.wikipedia.org/wiki/Unified_Deep_Water_System_of_European_Russia#cite_note-RosTransportArticle-1

**Note, a separate issue will be filed with further details on what rivers of the Unified Deep Water System of European Russia should have their min_zoom levels modified to 4.0, as well as what rivers are missing from 10m_rivers_lake_centerlines_scale_rank, ne_10m_rivers_europe, and 50m_rivers_lake_centerlines_scale_rank shapefiles.

**Comment by elliotap** [comment]
Can you diagram the extent of the unified deep water system? I’m typing from my phone right now so limited capability but would be interested to see interactions with the seas (esp. Sea of Azov/Black Sea)

**Comment by nvkelso** [comment]
Seems like a few of these are `Canal`, so let's mark their Feature Class as such when appropriate.

From [morflot.ru](http://eng.morflot.ru/activities/vvt.html): 

![image](https://user-images.githubusercontent.com/853051/111078715-21bdd200-84b4-11eb-8b5d-17877856587c.png)

From [unece.org](https://unece.org/fileadmin/DAM/trans/doc/2018/sc3wp3/5.8_NONIUS_Engineering.pdf):

![image](https://user-images.githubusercontent.com/853051/111078828-a6105500-84b4-11eb-8509-3ccd5a0fe80a.png)

![image](https://user-images.githubusercontent.com/853051/111078834-ad376300-84b4-11eb-87ae-b8e292dda63d.png)

![image](https://user-images.githubusercontent.com/853051/111078844-b6283480-84b4-11eb-9f1e-934afcacba1a.png)

From [Wikipedia](https://en.wikipedia.org/wiki/Unified_Deep_Water_System_of_European_Russia#cite_note-RosTransportArticle-1): 

![image](https://user-images.githubusercontent.com/853051/111078853-c213f680-84b4-11eb-862c-502a6159a43d.png)

**Comment by nvkelso** [comment]
I agree that a **min_zoom** of `4.7` be applied all/most of big rivers in the maps above (excluding Wikipedia which has too many rivers) should be included in the 50m rivers theme, including the canals. Existing min_zoom range from 4.7 to 5.0 to 6.0 and are spread over the 10m basic and Europe supplemental and 50m theme files (don't change min_zoom < 4.7). So a few features will need to be moved and generalized, too. The min_zoom needs to be applied to lake centerlines, not just the river segments.

![image](https://user-images.githubusercontent.com/853051/111231950-5b233a00-85a7-11eb-8385-7c77dba75cd4.png)

![image](https://user-images.githubusercontent.com/853051/111232270-016f3f80-85a8-11eb-8500-37a7a923baf7.png)

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/525.
