### ISSUE TITLE
10 & 50m lakes: Request to remove Lop Nur

### ISSUE THREAD

**Issue by elliotap** [nvkelso/natural-earth-vector#341]
Requesting Lop Nur be removed from these layers, because it has dried up to the degree that is no longer a water feature. https://en.wikipedia.org/wiki/Lop_Nur

**Comment by nvkelso** [comment]
Perhaps keep it as a different feature class? Needs more research.

**Comment by MrGawsome** [comment]
After some research, I think changing Lop Nur into a historic lake would be ideal here since the lake is dried up and is now a nuclear test site. We can remove ne_id 1159114133 and ne_id 1159114133 from the ne_10m_lakes and ne_50m_lakes shapefiles and add them to the ne_10m_lakes_historic and ne_50m_lakes_historic shapefiles respectively. 

Besides the already cited wikipedia link that suggests this lake is dried up and is now a nuclear test site, other sources suggest the same thing. See below for more information on the lake:
https://www.wikidata.org/wiki/Q319412
https://visibleearth.nasa.gov/images/43005/lop-nur-china
https://earthobservatory.nasa.gov/images/51039/lop-nur-xinjiang-china
http://large.stanford.edu/courses/2018/ph241/buchanan1/

What do you guys think about this proposal?

**Comment by nvkelso** [comment]
That's an intriguing proposal. There's already a playa feature there, I'm into this change.

![image](https://user-images.githubusercontent.com/853051/110419489-4813e580-804e-11eb-8ae0-8ab6583e32cc.png)

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/525.
