### ISSUE TITLE
10m & 50m lakes: extent of Lake Urmia has decreased significantly

### ISSUE THREAD

**Issue by elliotap** [nvkelso/natural-earth-vector#351]
Lake Urmia, in northwestern Iran, has dried up and decreased in area significantly. Areas that were formerly covered by water are now covered by salt. The natural earth features no longer reflect the extent of the lake.

See: https://www.npr.org/sections/pictureshow/2019/11/12/751360322/the-death-and-life-of-irans-lake-urmia
https://en.wikipedia.org/wiki/Lake_Urmia#Falling_level_and_increasing_salinity
https://en.wikipedia.org/wiki/File:Lake_Urmia_Google_Earth_Timelapse_1984%E2%80%932018.webm

**Comment by MrGawsome** [comment]
After conducting more research and discussing with Elliot, Elliot and I think it is best if we don't edit Lake Urmia anymore due to recent lake growth. It seems like the lake has recently increased its surface area, and NE’s lake geometry seems close enough to recent imagery. Also, OSM, Google, and Apple have geometries similar to NE, suggesting that NE's geometry may be close enough to imagery.

Here is some research I did to support Lake Urmia's recent and continued growth, suggesting that we don't need to edit its geometry anymore:

“By late 2020, the lake had been significantly restored and tourists welcomed the return of the waters” says a 02/2021 BBC article: https://www.bbc.com/future/article/20210225-lake-urmia-the-resurrection-of-irans-most-famous-salt-lake

Recent Tehran Times articles describing its recent growth: 
https://www.tehrantimes.com/news/458233/Japan-UNDP-continue-support-to-restore-Lake-Urmia  https://www.tehrantimes.com/news/456255/Lake-Urmia-s-surface-area-doubled-in-6-years

I didn’t find 2021 or 2020 aerial images of the lake but here are some 2019 images that show growth from 2018: 
https://modis.gsfc.nasa.gov/gallery/individual.php?db_date=2019-07-15
https://earthobservatory.nasa.gov/images/144848/reviving-the-shriveled-lake-urmia?fbclid=IwAR2ybV50orL0NI0j0QmAzcl0rAPC-ipNbjKGVcrcOWKxO61PLVdB1jTYxyo
https://www.tehrantimes.com/news/435130/Too-precious-to-lose-What-brought-back-Lake-Urmia-to-life

**Comment by nvkelso** [comment]
Interesting. No action is always the easiest action. Closing (until the rain stops, at least).
