### ISSUE TITLE
10m populated places: Request to remove ghost town 

### ISSUE THREAD

**Issue by elliotap** [nvkelso/natural-earth-vector#356]
Noginsk, Krasnoyarsk Krai, Russia, is a ghost town, abandoned in 2006. In 10m populated places, it has population info copied from the city of Noginsk in the Moscow region. The former feature with ne_id=1159137287 should be removed from populated places data.

see: 
https://en.wikipedia.org/wiki/Noginsk,_Krasnoyarsk_Krai
https://en.wikipedia.org/wiki/Noginsk

**Comment by nvkelso** [comment]
The `Noginsk` near Moscow with **ne_id** of `1159137287` and is a legit place and should **not** be deleted.

I agree the other `Noginsk` away in Siberia with **ne_id** of `1159146611` is a ghost town. We have **featurecla** = `Historic place` for that. I recommend changing the feature class instead of deleting as it does appear on most print atlases and is historically significant.

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/457.
