### ISSUE TITLE
10m admin1 poly label Moskovsskaya misspelling

### ISSUE THREAD

**Issue by jwva** [nvkelso/natural-earth-vector#363]
In the 10m admin1 poly labels, Moskovsskaya (Russia) should be with one s, i.e. "Moskovskaya".

**Comment by nvkelso** [comment]
Thanks for all the reports! I'm a little backed up right now but hope to make the corrections soon. In the meantime, please keep the reports coming, I appreciate them :)

**Comment by jwva** [comment]
Hi Nathaniel, thank you for the "sign of life". No sweat, please don't feel pressured. I must say you've done a marvelous job with Natural Earth data. Highly usable. Congratulations, keep it up! I'm a Dutch data scientist and cartographer myself, and I'm already enjoying the flexibility of this data in map-making. Shortly I'd like to make some contributions to the data myself, especially in India/China. I'll contact you separately about this.

**Comment by elliotap** [comment]
Confirmed - see romanization in https://en.wikipedia.org/wiki/Moscow_Oblast

**Comment by elliotap** [comment]
Confirmed - see romanization in https://en.wikipedia.org/wiki/Moscow_Oblast

Compare to Apple: 
<img width="1398" alt="Screen Shot 2021-03-17 at 11 37 25 AM" src="https://user-images.githubusercontent.com/64806657/111520372-44025a80-8715-11eb-9ac9-aae78d5350d2.png">

Google:
<img width="1680" alt="Screen Shot 2021-03-17 at 11 38 54 AM" src="https://user-images.githubusercontent.com/64806657/111520569-78761680-8715-11eb-9e5d-beceefb9661a.png">

OpenStreetMap:
<img width="1680" alt="Screen Shot 2021-03-17 at 11 39 33 AM" src="https://user-images.githubusercontent.com/64806657/111520600-7e6bf780-8715-11eb-8e24-f13f13cfedf7.png">

Surrounding features have name syntax like name=name (no Oblast), namealt= Name+"skaya Oblast"
Proposed Edits:
Change name from Moskovsskaya to Moscow (although Moscow, the city, is not located within the oblast, I believe this to be the on-the-ground name in english texts. "-ская"/"-skaya" indicates descriptive/prepositional relationship, from what I can gather, so Moskovskaya Oblast would be something like "Oblast with characteristics of Moscow", which functions better in the namealt that follows here)
Change namealt from Moskovsskaya Oblast to Moskovskaya Oblast

Also, in the course of looking at these features, I noticed that Russia's 3 federal cities (Moscow, St. Petersburg, Sevastopol), had type="oblast" or "Gorsovet", but these places are distinct types of administrative district (https://en.wikipedia.org/wiki/Federal_subjects_of_Russia#Types)

Proposing changing type value to "Federal City" or similar for features 1159313099, 1159313165, and 1159315877

**Comment by nvkelso** [comment]
Generally I've followed the rule of thumb that the city gets the generic name, and the surrounding region gets a disambiguation name in Who's On First, but that isn't applied consistently in Natural Earth. For instance **ne_id** = `1159317131` and `1159309705` for `Buenos Aires` in Argentina are counter to that.

For **ne_id** = `1159313163` (for the region excluding / surrounding the capital city of Moscow), let's go with the original proposed **name** = `Moskovsskaya` and asunder changes as necessary. 

(no op) For consistency let's keep **ne_id** = `1159313165` with **name** = `Moskva` (instead of changing it to `Moscow`). The name translations scramble all these in odd ways but so it is.

I agree with the **type_en** = `Federal City` (and associated **type** in Russian) change for **ne_id** = `1159313099`, `1159313165`, and `1159315877`.

The following images are labeled with `name_en` from Wikidata.

![image](https://user-images.githubusercontent.com/853051/111737020-18c65b00-883c-11eb-888f-536fd01f9894.png)

![image](https://user-images.githubusercontent.com/853051/111737036-1e23a580-883c-11eb-8b16-2942156deb80.png)

![image](https://user-images.githubusercontent.com/853051/111737195-65aa3180-883c-11eb-82a7-2e3a235c969f.png)

**Comment by nvkelso** [comment]
Process detailed in https://github.com/nvkelso/natural-earth-vector/issues/396#issuecomment-789428141.

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/516.
