### ISSUE TITLE
10m rivers: Huang (at Dongying, China) stopt just short of the Bo Hai

### ISSUE THREAD

**Issue by jwva** [nvkelso/natural-earth-vector#375]
In the 10m rivers data set, the Huang river stops just before it reaches the Bo Hai. Suggestion: extend the river line to touch the coast line.

**Comment by MrGawsome** [comment]
Can confirm that the Huang river doesn't extend to the 10m coastline. Following Bing Aerial imagery, I suggest that the river be snapped to the coastline at 37.77762664, 119.23443574 on the ne_10m_rivers_lake_centerlines and ne_10m_coastline shapefiles. 

Also, I checked the 50m and 110m river and coastline layers, and no issues were found there, so only the 10m file should be edited.

Lastly, I noticed similar issues for some of the nearby rivers. Some other 10m rivers in China, as well as some 10m rivers in Korea and Japan, don't extend to the 10m coastline. I will file a separate issue for these problems. Thanks

**Comment by nvkelso** [comment]
Sounds good, let's do it!

**Comment by MrGawsome** [comment]
Nearby river issues that can be fixed too:
Luan River (ne_id 1159128523) can be extended to 39.42959019, 119.30388143
Nakdon River (ne_id 1159127153) can be extended to 35.13441759, 128.95975794

I noticed various other rivers are closer to their coastlines but still slightly don’t align to them, such as Tone River in Japan (ne_id 1159126711). I assume these don’t need to be fixed because they look close enough to the coastline when zoomed out? Or should these issues be fixed as well? See the below screenshot for more information:
![image](https://user-images.githubusercontent.com/78829897/111508168-a143df00-8708-11eb-9376-7eec107ecfaf.png)

**Comment by nvkelso** [comment]
> I noticed various other rivers are closer to their coastlines but still slightly don’t align to them, such as Tone River in Japan (ne_id 1159126711). I assume these don’t need to be fixed because they look close enough to the coastline when zoomed out? Or should these issues be fixed as well? See the below screenshot for more information:

You're zoom (scale) is 1:26k but Natural Earth is only good until 1:1M scale (nominally 1:10M but over zooms). So if there is an obvious gap at 1:1M scale then eligible for a fix. But this type of precision is not necessary to fix or considered an error.

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/525.
