### ISSUE TITLE
10m airports: Haneda Airport, Suvarnabhumi Airport missing from Airport list

### ISSUE THREAD

**Issue by jingkai02** [nvkelso/natural-earth-vector#386]
The data for Haneda Airport and Suvarnabhumi Airport is not in the list of airports in the 1:10m data

**Comment by elliotap** [comment]
Verified - both airports handle in range of 50-100m passengers annually
https://en.wikipedia.org/wiki/Suvarnabhumi_Airport
https://en.wikipedia.org/wiki/Haneda_Airport

Proposed Changes: add the following two features - copied scalerank, featurecla, type from ATL because these airports are also of global significance

lat/lng | 35.55009719017344,   139.78639709407628 | 13.692563388870756,   100.75058446632434
-- | -- | --
scalerank | 2 | 2
featurecla | Airport | Airport
type | major | major
name | Tokyo Int'l | Suvarnabhumi Airport
abbrev | HND | BKK
location | terminal | terminal
gps_code |   |  
iata_code | HND | BKK
wikipedia | https://en.wikipedia.org/wiki/Haneda_Airport | https://en.wikipedia.org/wiki/Suvarnabhumi_Airport
natlscale | 150 | 150
comments | aka Haneda Airport | aka Bangkok Airport
wikidataid | Q204853 | Q194316
name_ar | from wikidata | from wikidata
name_bn | from wikidata | from wikidata
name_de | from wikidata | from wikidata
name_en | from wikidata | from wikidata
name_es | from wikidata | from wikidata
name_fr | from wikidata | from wikidata
name_el | from wikidata | from wikidata
name_hi | from wikidata | from wikidata
name_hu | from wikidata | from wikidata
name_id | from wikidata | from wikidata
name_it | from wikidata | from wikidata
name_ja | from wikidata | from wikidata
name_ko | from wikidata | from wikidata
name_nl | from wikidata | from wikidata
name_pl | from wikidata | from wikidata
name_pt | from wikidata | from wikidata
name_ru | from wikidata | from wikidata
name_sv | from wikidata | from wikidata
name_tr | from wikidata | from wikidata
name_vi | from wikidata | from wikidata
name_zh | from wikidata | from wikidata
wdid_score | ? | ?
ne_id |   |  

How is wdid_score determined? And what is the usual source for gps_code?

**Comment by nvkelso** [comment]
The wikidata is score column should be removed all together.

The two airport codes are either 3 characters or 4 characters. I believe the 4 char one is the icao code, see the Wikipedia articles.

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/509.
