### ISSUE TITLE
Bug with Crimea. 

### ISSUE THREAD

**Issue by followtheblackrabbit** [nvkelso/natural-earth-vector#391]
Crimea is part of Russia on your map. But this is not true. Crimea is Ukraine. I'm sure this is a bug, can you fix it?

**Comment by Maxszik** [comment]
A search brings [this](https://github.com/nvkelso/natural-earth-vector/issues/302) and [this](https://github.com/nvkelso/natural-earth-vector/issues/177). I guess the creator is following the osm.org [on the ground rule](https://wiki.openstreetmap.org/wiki/Disputes#On_the_Ground_Rule), but we’ll have to wait for him to reply.

**Comment by Monstrofil** [comment]
@nvkelso could you please explain your changes of Ukraine/Russia border? As far as I know, only several countries recognise Crimea as part of Russia, while others, including EU and US, not.

**Comment by nvkelso** [comment]
It's not a bug. **Natural Earth** follows the "on the ground" rule. Specifically ([source](https://www.naturalearthdata.com/about/map-update-committee/)):

> Political features: Natural Earth’s shows the de facto administrative and sovereignty areas. We often show the disputed areas, too, so you can repurpose to suit your needs.

That said, we recognize this doesn't work for everyone (either for Crimea or a surprising number of border disputes around the world) so we are working on v5 which will offer pre-built admin-0 country themes and extra properties in the disputed and other themes that are optimized for different points of views (worldviews). 

In the meantime you'd need to use either an earlier version of Natural Earth (eg in the v3 series) or use the disputed areas in v4 to modify the admin-0 country on your own.

**Comment by zhangshine** [comment]
Point(34, 46)

https://github.com/zhangshine/BGJar/blob/92dc8f9e58327cc276fc9667885b09b0aed84516/src/pages/world-map/data/ne_10m_admin_0_countries_1_2x2_country_locations.json#L75

**Comment by gerasimvol** [comment]
There are no discussions about Crimea. Whole world recognizes it as Ukraine, as it always was. We don’t accept any special settings, admin-0 options or any other mess.

**Comment by nvkelso** [comment]
Here's the state of things in `version 5` of Natural Earth which introduces optional "point-of-view" (POV) or "worldview" for administrative geographies. Version 5 will be released soon, and these changes are available as a branch in this Github repo.

**Specifically, version 5 of Natural Earth:**

1. Adds support for alternate points of view in admin-0 related themes with `fclass_*` properties (like `fclass_iso`).
     - The following country and international organizations worldviews are supported:
         - Argentina (`ar`), Bangladesh (`bd`), Brazil (`br`), China (`cn`), Egypt (`eg`), France (`fr`), Germany (`de`), Greece (`gr`), India (`in`), Indonesia (`id`), Israel (`il`), Italy (`it`), Japan (`jp`), Morocco (`ma`), Nepal (`np`), Netherlands (`nl`), Pakistan (`pk`), Palestine (`ps`), Poland (`pl`), Portugal (`pt`), Russia (`ru`), Saudi Arabia (`sa`), South Korea (`ko`), Spain (`es`), Sweden (`se`), Taiwan (`tw`), Turkey (`tr`), United Kingdom (`gb`), United States (`us`), Vietnam (`vn`), ISO (`iso`)
    - Fixes #301 (and this issue #391 which has a rich comment thread)
2. Provides easy alternate download of `ne_10m_admin_0_countries` themes preassembled for the 31 different viewpoints, like `ne_10m_admin_0_countries_arg` for Argentina.
     - Full list of countries: 
         - Argentina (`arg`), Bangladesh (`bdg`), Brazil (`bra`), China (`chn`), Germany (`deu`), Egypt (`egy`), Spain (`esp`), France (`fra`), United Kingdom (`gbr`), Greece (`grc`), Indonesia (`idn`), India (`ind`), Israel (`isl`), Italy (`ita`), Japan (`jpn`), South Korea (`kor`), Morocco (`mar`), Nepal (`nep`), Netherlands (`nld`), Pakistan (`pak`), Poland (`pol`), Portugal (`prt`), Palestine (`pse`), Russia (`rus`), Saudi Arabia (`sau`), Sweden (`swe`), Turkey (`tur`), Taiwan (`twn`), Ukraine (`ukr`), United States of America (`usa`), and Vietname (`vnm`).
    - Fixes #301
3. Expands the name localization added in v4.1 to 25 languages (up from 21) so POV can be matched with localized labels.
    - Adds Farsi (`fa`) for Iran, Hebrew (`he`) for Israel, Ukrainian (`uk`) for Ukraine, and Urdu (`ur`) for Pakistan.
    - Localized names in the original 21 languages have also been updated.
    - Fixes #302

**Now back to the situation between Ukraine and Russia:**

_(below)_ The **default** boundaries and country boundary remain **defacto** and don't change from version 4, here with **English** labels.

_Note how the breakaway area of Donbas has a dashed line (while still being salmon colored for Ukraine even though it no longer controls the territory on the ground) and the two edge boundaries of Crimea are shown as disputed (while Crimea and Sevastopol are blue background as Russia administers those areas on the ground)._

![image](https://user-images.githubusercontent.com/853051/127813805-8bea546c-b41e-4de4-9bc2-f68ef400c9bf.png)

_(below)_ However, version 5 introduces new attributes allowing one to match the **Ukrainian** labels with Ukraine point-of-view on the boundaries and country polygons. 

_Note how the Donbas breakaway area boundary line is no longer shown, and landward Crimea boundary is shown as an admin-1 line, and the exterior Crimea boundary is shown as a country boundary (with Crimea and Sevastopol are salmon background as Ukraine claims those areas)._

![image](https://user-images.githubusercontent.com/853051/127814193-acee31c3-fb0e-4fd5-b65e-64834979bf68.png)

(below) Same for Russian POV here with **Russian** labels.

_Note Donbas as unspoken and the landward Crimea boundary as the solid black country boundary line (with Crimea and Sevastopol as blue background as Russia claims and administers those areas on the ground)._

![image](https://user-images.githubusercontent.com/853051/127813246-61afc2ef-4cfb-42e2-b9ca-b25c49f835ce.png)


**Again, with the disputed polygons:**

(below) Showing English labels, we see two disputed areas for Crimea and Donbas in the underlying data:

![image](https://user-images.githubusercontent.com/853051/127812608-64198057-0fd3-463c-96ce-6012db604a97.png)

There is recognition that the situation remains complicated. But this new version provides a data-driven way to match local expectations all while preserving Natural Earth's commitment to showing the defacto state of the world. That's not without controversy, but should be more useful to more people than the current state in version 4.

**Comment by rshopa** [comment]
@nvkelso 
> The default boundaries and country boundary remain defacto and don't change from version 4, here with English labels.

I **strongly disagree** and **shall report** wherever possible this issue, as the developers ostensibly violate the International Law. UN statement, all Western countries, most of the rest of the world clearly stated that they support the integrity of Ukraine and recognise its borders as of the beginning of 2014. Crimean Peninsula is not even disputed under Ukrainian law, it is "temporarily occupied". 

One more, I stress that the so-called "de-facto" status, even if introduced, is highly unpractical since it's difficult to achieve consistency. For instance, it does not depict other territories, occupied and controlled by Russia - Transnistria, occupied Donbass, DE-FACTO even Belarus. I suspect the same is about Tskhinvali and Abkhazia (nor painted in "russian"). Moreover, the ongoing conflicts (such as between Azerbaijan and Armenia) might change borderlines on a daily basis, rendering such map obscured. 

The only logical reason this so-called "de-facto" version exists is that the developers did not act in good faitn and their goal was ONLY to justify the Crimean occupation. Therefore, **I consider you and the Natural Earth team as those who support terrorist acts, invasion and mass-murder made by Russian Federation and question the Ukrainian sovereignty**, by introducing this so-called "de-facto" formula. I also encourage the rest of the people who had left the post here to make similar statements. 

The "russian" version should not be exist in the first place as it justifies the war crimes. I considered it the same as if, e.g. you added the ISIS or Taliban version of the map.

**Comment by Monstrofil** [comment]
I'm a bit confused with your "defacto" usage... why Crimea is so special in this region? Why is Transnistria marked as Moldova teritory and Donbass is marked as part of Ukraine in default worldview, but Crimea is not? 

I'm totally accepting existence of multiple worldviews (e.g. Russian one where Crimea would me marked as "Республика Крым") just because some countries have their own laws that don't match most of the other world. But global DEFAULT view must match most (if not all) international laws and views. Making Crimea as part of Russia by default makes much more people around the world to change their maps manually.

**Comment by anxolerd** [comment]
@nvkelso

As Ukrainian citizen I am deeply offended with you de-facto supporting terrorism by recognizing and ACCEPTING Crimea occupation with Russia. I totally agree with @rshopa, that 

> The "russian" version should not exist in the first place as it justifies the war crimes. I considered it the same as if, e.g. you added the ISIS or Taliban version of the map.

It's not just me being offended. By doing the thing, you are de-facto (I see, you love this word to justify the crimes and insults) telling the whole nation of Ukrainians: "hey you stupid, take this PoV feature to fullfill your fantasies about Crimea, as it will never be yours". This is definitely unacceptable.

**Comment by forrester86** [comment]
Crimea is Ukraine! The whole world adheres to this point of view!

**Comment by lietto** [comment]
People use maps to know about the world and countries more. And with this "de-facto" and POV usage you mislead this people with wrong info. We have UN and different international laws and  we should use them to show the real borders of the countries. Of course you should show additional info about occupied and disputed areas but borders should be "de jure".

**Comment by nvkelso** [comment]
The PR https://github.com/nvkelso/natural-earth-vector/pull/446 described in https://github.com/nvkelso/natural-earth-vector/issues/391#issuecomment-890772203 has been merged. Closing this issue.

**Comment by FormerlyChucks** [comment]
hi carp

**Comment by n0rdlicht** [comment]
Quite disappointing and upsetting to see a popular and trusted global dataset, among other things, representing politics in any other way than agreed by the UN. While complicated for sure, I'm not able to fathom how this can be. @nvkelso: please simply state that you are rejecting the UN as legitimate and we can move on and establish a new dataset. While the UN has no doubt failed in many regards it still embodies the hope and dream of humans cooperating peacefully through diplomacy rather than force and whoever is more powerful. You and everyone arguing for the "on-the-ground-rule" are unfortunately choosing the latter without even recognising as pointed out above 😔 And no, adding a way to represent different POVs is not a solution, other than at a minimum discarding the rule of law in a fundamental way. Extremely disappointing and sad.

FYI how I got to this thread today: simply browsing the wonderful maplibre landing page, using a demo tileset based on this one and being very disturbed by Crimea showing up as Russian territory, no indication of any sorts right next to a logo modified to show support for Ukraine.

**Comment by SeriyBg** [comment]
Today, after the world discovered the russian atrocities, the war crimes, and the unprovoked war unleashed by russia, the author is still disgracefully chosen to use an excuse for justifying the illegal annexation of Crimea!
This goes against international law, against the UN statements, and supports terrorism!

**Comment by webcaptcha** [comment]
Can we apply to court and ban @nvkelso on the GitHub because he is violating US laws.

**Comment by rshopa** [comment]
@webcaptcha agree: probably only a federal lawsuit can make this crime be resolved.

**Comment by OrchidSoleil** [comment]
Natural Earth team's stance on the issue of occupied Crimea showing as a Russian territory by default is appalling. Why don't you mark Crimea a Ukrainian territory by default and force Russia to apply its crooked 'worldview' is beyond me. Russia is a state sponsor of terrorism after all. Unless Russia bribes you, of course. Your 'de facto/de jure' argument stands no ground, as people already pointed out. By supporting this version of the map you support atrocities and deportations that Russians  commit in Crimea and in Ukraine since 2014.  I'll continue raising this issue wherever possible.

**Comment by rshopa** [comment]
@OrchidSoleil I also noticed @nvkelso closes almost every issue here reporting the "bug with Crimea", without any explanation and consensus reached. I suspect he's preventing the fact of consciously denying the sovereignty of Ukraine by himself and the Natural Earth go viral. 

I also believe it can no longer be considered a conventional tech issue which can be resolved in traditional way, since a felony of such scale during the genocidal war requires a legal consequences. This cannot be left out unpunished even if GitHub intervenes directly (it did not).

**Comment by OrchidSoleil** [comment]
@rshopa i certainly agree with you that something's fishy going on here. They just refer us to Natural Earth's statement on 'disputed territory', in which they also take russia's side by default and force Ukraine and the rest of the world to apply 'POV', as they call it, when in fact, it's russia's 'POV' doesn't comply with the rest of the world. And it is disturbing. 'POV' of aggressor is always victim blaming, the same way russia blames Ukraine for russian invasion. Illegal occupation and deportation is not a worldview, I'm sorry, it is an international crime. 
But I've found out yesterday, that this issue of assigning specifically Crimea to russia on maps, declaring it 'de facto' russian, goes even deeper. Along with Natural Earth, another major map source, OpenStreetMap Foundation, also assigns Crimea to russia with exactly the same 'explanation'. Here it gets even worse. Two days ago I've seen one of such maps in Washington Post, used by Institute for the Study of War, alas unknowingly,  where you can clearly see the border between Ukraine and Crimea.

**Comment by margaretcourant-maker** [comment]
> A search brings [this](https://github.com/nvkelso/natural-earth-vector/issues/302) and [this](https://github.com/nvkelso/natural-earth-vector/issues/177). I guess the creator is following the osm.org [on the ground rule](https://wiki.openstreetmap.org/wiki/Disputes#On_the_Ground_Rule), but we’ll have to wait for him to reply.

If they followed the on the ground rule, why wouldn't Kosovo show as Kosovo? Currently, it shows as Serbia - but in some datasets, such as the "US Worldview" one, it shows as Kosovo. But the reality is that on the ground, Kosovan authorities control the area. It's strange that the on the ground rule would apply to Crimea but not to Kosovo. 

Russia views Kosovo as Serbian, particularly because Russia is sensitive about supporting any independence movement anywhere as they don't want to embolden independence movements in places like Chechnya. 

To me, it's concerning that Crimea would be considered Russian because of the on the ground rule and Kosovo would be considered Serbian. Not only is that a contradiction, but also both are viewpoints that Russian influence tries to assert. It should raise questions.

On the ground, Kosovo has had continuous, effective, independent control of its territory since 1999, with Serbian authorities exercising no meaningful governance there. The fact that Kosovo shows up as Kosovo in many of the world view files means that Natural Earth already acknowledges the ambiguity here.

That implicitly admits:
- The choice is not technical
- The default dataset encodes a specific geopolitical stance, while claiming neutrality via the “on-the-ground” rule

Once you say “we follow on-the-ground reality,” you don’t get to selectively fall back on legal sovereignty only when it aligns with certain states’ positions. In this case it happens to be the Russian state's position, and that makes the Crimea decision look even worse.

**Comment by mauriceboe** [comment]
**@nvkelso — TREK is dropping Natural Earth, and you should know exactly why.**

We maintain [TREK](https://github.com/mauriceboe/TREK), a self-hosted travel planner that shipped Natural Earth boundaries. As of now we're gone — migrated to a source that defaults to internationally recognized borders, because that is the one thing you keep refusing to do.

You've defended the "de facto / on-the-ground" rule at length in this thread as if it were neutral. It isn't, and your own dataset proves it, because you don't actually apply it:

- Crimea → **Russia**. Yet Kosovo → **Serbia**, after 25+ years of continuous independent Kosovar control. Transnistria → **Moldova**. Northern Cyprus → **Cyprus**. Donbas → **Ukraine**.

Every one of those contradicts your own stated principle — and every one breaks in the direction that does *not* endorse a Russian land grab. The single place "on-the-ground" is enforced to the letter is the exact place the Russian Federation wants it enforced. That isn't a methodology, it's a political position with a neutral-sounding alibi — and you are the person who keeps it the default.

Telling Ukrainians to "use the POV layer" to opt out of seeing their occupied territory painted as Russian isn't a compromise. It makes the UN-68/262, internationally-recognized border the *opt-in* and the occupier's claim the default. You inverted the burden, and then defended it.

We won't ship that to our users. One default flipped and you'd keep dozens of downstream projects; you chose not to. Noting it here so the choice stays attached to the person who made it.

**Comment by webcaptcha** [comment]
@nvkelso is just supporting rUssian fascists and should be banned on Github

**Comment by lynxeyedua** [comment]
Hey! I also found by accident that Crimea is incorrectly mapped as part of russia. 

Thanks for work done, but it's not right that maps by default use this version.

I want to see Crimea as part of Ukraine, because this is officially recognised by UN borders.

It's illegal to use such map where Crimea is not part of Ukraine in my country.

Explanation is that for some reason people want to map reality on the ground or show conflicts on the map. But its also not correct, not from UN point of view, not correct from reality (there are a lot more conflicts on the ground from shown), not correct from rashist point of view (they officially join not only Crimea but 4 other Ukraine regions, even not occupied, this is in their shittystitution):
- Actual situation on the ground: [deepstate map](https://deepstatemap.live/en#7/48.7416305/35.3979492) - Russia occupy a lot more than "just" Crimea. Also don't forget to daily update front progression.
- Official UN map: [official UN map inc. disputed regions](https://www.un.org/geospatial/content/map-world-1) - Crimea is Ukrainian clearly

So either follow official maps, or explain why its done so - because the map is wrong from any point of view (reality vs official), and by using official versions a lot of pain can be removed.

Thank you in advance.
