### ISSUE TITLE
Separate Telangana from Andhra Pradesh

### ISSUE THREAD

**Issue by Nate-Wessel** [nvkelso/natural-earth-vector#396]
From 2014: See e.g.
* https://www.news18.com/news/politics/andhra-pradesh-split-indias-29th-state-telangana-is-born-691955.html
* https://en.wikipedia.org/wiki/Telangana

**Comment by nvkelso** [comment]
Thanks for these issues, please keep them coming!

If I might ask, what mapping project are you working on that takes you to this part of the world?

**Comment by Nate-Wessel** [comment]
@nvkelso I'm making a variety of policy-related maps for the Asia Pacific Foundation of Canada. We've got people tracking quite a few Asian countries, so you may well be getting more updates from me in the future as we start to do more to add a spatial component to our publications :-)

Thanks for your work on this!

**Comment by nvkelso** [comment]
Scheduled for v5.1 milestone. I agree the inland portion should be split off with **name** = `Telangana`, and the remaining coastal portion should retain **name** = `Andhra Pradesh`. The **wikidata_id** is [Q677037](https://www.wikidata.org/wiki/Q677037). There are a few other properties you can copy over from the one state to the new one. But some of the concordances, populations & etc should be researched fresh and updated for both. Also set the new **ne_id** from Brooklyn Ints. 

Editing the admin-1 themes can be "fun". You do NOT edit the polygon theme. Instead, polygons in Natural Earth are "built" using linestring inputs, turned into output polygons (assuming geometries are snapped) with Mapshaper, and then label points add in a unique ID, and the attributes are joined from another table for the final "download ready" shapefile. This allows all the physical land, ocean, admin-0 themes, and admin-1 themes to all "fit" and "nest" together... without needing advanced topology config in software like PostGIS. Dumb stupid but it works, and Mapshaper is fast and open source.

NOTE: This Indian state is only (for now) in the 1:10m theme, so you won't need to update the 1:50m theme just yet.

This part of the Makefile has the recipe and lists which themes are implicated:

- https://github.com/nvkelso/natural-earth-vector/blob/master/Makefile#L435-L464

Specifically, load the following themes into QGIS:

- 10m_cultural/ne_10m_admin_0_boundary_lines_land.shp
- 10m_cultural/ne_10m_admin_0_boundary_lines_map_units.shp
- 10m_physical/ne_10m_coastline.shp
- 10m_physical/ne_10m_minor_islands_coastline.shp
- 10m_cultural/ne_10m_admin_1_states_provinces_lines.shp
- 10m_cultural/ne_10m_admin_1_seams.shp
- 10m_cultural/ne_10m_admin_1_label_points.shp
- 10m_cultural/ne_10m_admin_1_label_points_details.dbf
- intermediate/ne_10m_lakes_big.shp
- 10m_physical/ne_10m_lakes.shp

The primary files you need to **modify** are:

- ne_10m_admin_1_states_provinces_lines.shp
- 10m_cultural/ne_10m_admin_1_label_points.shp
- 10m_cultural/ne_10m_admin_1_label_points_details.dbf

The `lines` allows you to split or join polygons depending on what's happening with the administrative geography. Make sure "snapping" is turned on in QGIS for all the active themes listed above. Otherwise the polygon "cracking" won't work.

The `label_points` file gives the resulting built polygon an ID, this is "housekeeping" file just in the NE repo not for public download on the site. There should only be 1 label point per output polygon. So if you're splitting a feature add a new label point. If you're merging polygons delete one of the extra points.

The ID needs to be reflected in the `label_points_details` as a row, and the attributes are copied from this "housekeeping" file into the output SHP.

If you need to change a name (or other attribute) and not the geometry, then just edit `label_points_details` and run the make target like (assuming Mapshaper is installed):

> make build_a7_ne_10m_admin_1_all

You'll see output like:

```
mkdir -p intermediate
mapshaper -i 10m_physical/ne_10m_lakes.shp \
		-filter 'scalerank <= 0' + \
		-o intermediate/ne_10m_lakes_big.shp \

[filter] Retained 18 of 1,354 features
[o] Wrote intermediate/ne_10m_lakes_big.shp
[o] Wrote intermediate/ne_10m_lakes_big.shx
[o] Wrote intermediate/ne_10m_lakes_big.dbf
[o] Wrote intermediate/ne_10m_lakes_big.prj
mapshaper -i combine-files snap \
		10m_cultural/ne_10m_admin_0_boundary_lines_land.shp \
		10m_cultural/ne_10m_admin_0_boundary_lines_map_units.shp \
		10m_physical/ne_10m_coastline.shp \
		10m_physical/ne_10m_minor_islands_coastline.shp \
		10m_cultural/ne_10m_admin_1_states_provinces_lines.shp \
		10m_cultural/ne_10m_admin_1_seams.shp \
		-filter-fields \
		-merge-layers \
		-polygons gap-tolerance=1e-4 \
		-join 10m_cultural/ne_10m_admin_1_label_points.shp \
		-filter 'adm0_sr !== null' + \
		-o 10m_cultural/ne_10m_admin_1_states_provinces_scale_rank_minor_islands.shp \
		-filter 'adm0_sr <= 6' + \
		-o 10m_cultural/ne_10m_admin_1_states_provinces_scale_rank.shp \
		-dissolve 'adm1_code' copy-fields=featurecla,scalerank \
		-join 10m_cultural/ne_10m_admin_1_label_points_details.dbf encoding=utf8 keys=adm1_code,adm1_code fields=* \
		-o 10m_cultural/ne_10m_admin_1_states_provinces.shp \
		-erase intermediate/ne_10m_lakes_big.shp \
		-o 10m_cultural/ne_10m_admin_1_states_provinces_lakes.shp \
#  calc='join_count = count()'
[i] Snapped 4636 points
[join] Joined 11,285 data records
[join] 4/11288 target records received no data
[join] 1/11288 target records were matched by multiple source records
[filter] Retained 11,284 of 11,288 features
[o] Wrote 10m_cultural/ne_10m_admin_1_states_provinces_scale_rank_minor_islands.shp
[o] Wrote 10m_cultural/ne_10m_admin_1_states_provinces_scale_rank_minor_islands.shx
[o] Wrote 10m_cultural/ne_10m_admin_1_states_provinces_scale_rank_minor_islands.dbf
[o] Wrote 10m_cultural/ne_10m_admin_1_states_provinces_scale_rank_minor_islands.prj
[filter] Retained 8,535 of 11,284 features
[o] Wrote 10m_cultural/ne_10m_admin_1_states_provinces_scale_rank.shp
[o] Wrote 10m_cultural/ne_10m_admin_1_states_provinces_scale_rank.shx
[o] Wrote 10m_cultural/ne_10m_admin_1_states_provinces_scale_rank.dbf
[o] Wrote 10m_cultural/ne_10m_admin_1_states_provinces_scale_rank.prj
[dissolve] Dissolved 8,535 features into 4,594 features
[join] Joined 4,593 data records
[join] 1/4594 target records received no data
[join] 54/4647 source records could not be joined
[o] Wrote 10m_cultural/ne_10m_admin_1_states_provinces.shp
[o] Wrote 10m_cultural/ne_10m_admin_1_states_provinces.shx
[o] Wrote 10m_cultural/ne_10m_admin_1_states_provinces.dbf
[o] Wrote 10m_cultural/ne_10m_admin_1_states_provinces.prj
[o] Wrote 10m_cultural/ne_10m_admin_1_states_provinces_lakes.shp
[o] Wrote 10m_cultural/ne_10m_admin_1_states_provinces_lakes.shx
[o] Wrote 10m_cultural/ne_10m_admin_1_states_provinces_lakes.dbf
[o] Wrote 10m_cultural/ne_10m_admin_1_states_provinces_lakes.prj
```

If you need to edit the geometry, or both... do that and then run the same command.

Sometimes in QGIS the 10m_cultural/ne_10m_admin_1_states_provinces.shp file is cached and the new result won't show. Work in a project document you can save. Exit and save the QGIS doc. Relaunch QGIS and open the document (should be keep the last viewport) and review the output.

When researching where the new geometry goes, link to a few sources in an issue comment here. Open data is great! But it often needs to be "downsampled" or "generalized" to match the vertex density in the NE theme and scale rank you're working in. Mapshaper.org can be good for that. Or freeform digitize. 

NOTE: If the boundary is along a river, do check the rivers themes (default and supplementary per continent) to see if that river is included already. If it is, you can copy it over to the rivers theme, adjust it's properties to taste, and press go. Sometimes just a portion of a boundary will follow the river. Other times it cuts in lines of latitude or longitude, or along a mountain crest. 

For illustative purpose only (as the new boundary is NOT correct):

- Add new boundary `line` between the two states, make sure snapping happens to existing lines so the polygon can be created.
- Add new `label_point` inside the new polygon. Make sure the old label point is inside the remaining old polygon (move it as neccesary).
- The new `label_point` should get a new **adm1_code** value, like `IND-10374` that is unique inside the DBF (there's no magic here... just sort on that column and increment the biggest **diss_me** value and concatenate that with the 3-char adm0_a3 code for the country you're working in). Generally copy the other values from the remaining old polygon's label point (assuming they are in the same country). But the **name** will come later from...
- Make sure there is a new row in `label_point_details` with the same new **adm1_code** value, like `IND-10374`. Just like the label point attributes, find the old label point's properties and mostly copy values over, and update properties like **name**, **wikidata_id**, concordances & etc. These are the actual values that get joined onto the output polygon. Name translations are added with a script later based on the Wikidata ID, so get that right! The details file also needs the new **ne_id** set, get a new [Brooklyn Integer](https://www.brooklynintegers.com/create/) for that.

![image](https://user-images.githubusercontent.com/853051/109753872-d47a6000-7b97-11eb-83b1-53212b6a9119.png)

**Comment by nvkelso** [comment]
Who's On First is my first reference for open data for admin polygons, and is more up-to-date than Natural Earth. In this case there is a record with polygon for the new state we can reference:

- https://spelunker.whosonfirst.org/id/1108805979/

![image](https://user-images.githubusercontent.com/853051/109755307-9df21480-7b9a-11eb-956d-a36c3f5fb320.png)

Note the "Download GeoJSON link" which gets you a file you can load into QGIS as reference. Occasionally the Spelunker is out of date... so following the View on Github link and getting the raw file from there can sometimes solve problems.

There's also a search box in the upper right corner of the site... and you can use the filter facets in the right sidebar to narrow the text search to "region" (eg state, province).

- https://spelunker.whosonfirst.org/search/?q=telangana&placetype=region

**Comment by nvkelso** [comment]
Flagging this for @elliotap so India updates are coherent across entire country.

**Comment by elliotap** [comment]
@nvkelso I've been holding off on admin 1s, but now ready to get going on them. With #508 ongoing and some populated places edits associated with the admin 1 changes, what sort of queue would you prefer for PRs?

**Comment by nvkelso** [comment]
Mostly a dup of https://github.com/nvkelso/natural-earth-vector/issues/234, but that issue also notes some capital city changes for populated places layer.

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/522.
