### ISSUE TITLE
10m populated places: Phnom Tbeng Meanchey is the name of a mountain

### ISSUE THREAD

**Issue by elliotap** [nvkelso/natural-earth-vector#408]
Phnom Tbeng Meanchey (ID: 1159120843) is given the name of a mountain. Sources indicate that the correct name for the urbanization is "Preah Vihear"

see: https://www.phnompenhpost.com/video/enjoy-stunning-phnom-tbeng-waterfall
https://en.wikipedia.org/wiki/Preah_Vihear_(town)
https://www.kathmanduandbeyond.com/preah-vihear-cambodia-contentious-angkorian-ruins/ (<- explains situation with temple of the same name)

**Comment by mizmay** [comment]
Verified! Preah Vihear is the name of the province and the name of a nearby temple as well as a municipality (Q27220327)
- This place is called Preah Vihear in Open Street Map https://www.openstreetmap.org/node/256992516
- This place is called Kampong Pranak in Google Maps, but then there is also a POI for Preah Vihear City Hall https://www.google.com/maps/place/Kampong+Pranak,+Cambodia/@13.8146049,104.9630808,14z/data=!3m1!4b1!4m13!1m7!3m6!1s0x3111812b80758a49:0x28b4a74e8e3474d8!2sPreah+Vihear,+Krong+Preah+Vihear,+Cambodia!3b1!8m2!3d13.7918616!4d104.9823722!3m4!1s0x311181d4c494e927:0xe768c76d648eb831!8m2!3d13.8114603!4d104.9781388 https://www.google.com/maps/place/Kampong+Pranak,+Cambodia/@13.8146049,104.9630808,14z/data=!3m1!4b1!4m13!1m7!3m6!1s0x3111812b80758a49:0x28b4a74e8e3474d8!2sPreah+Vihear,+Krong+Preah+Vihear,+Cambodia!3b1!8m2!3d13.7918616!4d104.9823722!3m4!1s0x311181d4c494e927:0xe768c76d648eb831!8m2!3d13.8114603!4d104.9781388
- There are search results for Preah Vihear on Apple Maps, but it's unclear whether it's resolving to the province or the city
- Google Maps agrees Phnom Tbeng Meanchey is a mountain, not a populated place https://www.google.com/maps/place/Phnom+Tbeng+Meanchey/@13.5982723,104.9778842,15z/data=!3m1!4b1!4m5!3m4!1s0x31118855eea0de2d:0x30d9fe9ec862cf29!8m2!3d13.5982727!4d104.986639
- Phnom Tbeng Meanchey resolves to an uncategorized POI in Apple Maps
- Phnom Tbeng Meanchey resolves to a restaurant in Open Street Map

Recommendations:
- Remove record for Phnom Tbeng Meanchey (no associated wikidata ID)
- Add record for Preah Vihear (Q27220327)

**Comment by nvkelso** [comment]
I recommend a name fix (rather than deleting feature and adding a new one). This Natural Earth feature was added to backfill missing admin-1 capitals. So if it has the wrong name, then let's fix that. That way their will be less churn.

- I see the following Wikidata ID on the existing feature: https://www.wikidata.org/wiki/Q2428308, which is for `Capital of the Cambodian province of Preah Vihear` which links to this Wikipedia (eng) page: https://en.wikipedia.org/wiki/Preah_Vihear_(town). 

I think the Wikidata ID is fine as-is? The proposed https://www.wikidata.org/wiki/Q27220327 looks to be for the administrative area instead of the capital locality? But the names of the Wikipedia pages linked are a mix of the funky name and the proposed (good) name.

**Comment by mizmay** [comment]
Thanks for the additional context @nvkelso, here's another source that says Phnom Tbeng Meanchey is the capital of the province of Preah Vihear. https://www.tourismcambodia.com/travelguides/provinces/preah-vihear.htm

Since some sources on maps and on the internet say the name of the capital is (town) is also Preah Vihear, let's resolve by adding "Preah Vihear" to NAMEALT.

**Comment by nvkelso** [comment]
Fixed via #457.
