### ISSUE TITLE
Add Salish Sea to marine label areas

### ISSUE THREAD

**Issue by nvkelso** [nvkelso/natural-earth-vector#41]
http://t.co/hk3GFI6m

The term Salish Sea is quite new, dating officially from 2010 when both Canadian and American geographical boards adopted the name. The sea comprises of the Strait of Gerogia, Pugeot Sound and Strait of Juan de Fuca. Think of it this way, imagine if the Mediterranean Sea was only known as a group of a dozen seas (Aegean, Ionian, Adriatic, Tyrrhenian, Cilician, Libyan, Crete, Ligurian, Belearic, Alboran Seas, etc.) but had no unifying name. Well that's the case with the Salish Sea. A combination of a national border and somewhat unique geography likely prevented a unified name. Thanks to geographic societies and professionals we now have a unified name. Quick question: Is the Johnstone Strait part of the Salish Sea? Should it be included?

**Comment by MrGawsome** [comment]
The Salish Sea is present in the ne_10m_geography_marine_polys shapefile already (see image below) and the polygon seems to have good attributes and it seems to cover the sea's region well enough according to the below sources. Does this sea need to be added in another shapefile? It is missing in the 50m and 110m marine polygon files, but I assume this is because the sea is too small to be included in those shapefiles.

![image](https://user-images.githubusercontent.com/78829897/110991822-f4ddb380-8329-11eb-9288-7a6aa8c5c2a7.png)

Here is general research I did to confirm the sea's name and extent of the sea. It seems to not include the Johnstone Strait as the previous github user almccon pointed out. Research:
Awesome map and description of the sea: https://www.seadocsociety.org/about-the-salish-sea
A US gov website that has another good map of the sea (map taken from University of Washington): https://www.epa.gov/salish-sea
Canadian gov website to confirm the name and general area of the sea: https://apps.gov.bc.ca/pub/bcgnws/names/53200.html
Wiki for general information: https://en.wikipedia.org/wiki/Salish_Sea
OSM: https://www.openstreetmap.org/node/1650976220#map=8/48.791/-122.720

**Comment by nvkelso** [comment]
Let's change the **min_label** to `6.0` for the existing Salish Sea feature in the 10m theme and call it a day (no other changes).

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/507.
