### ISSUE TITLE
Lakes Tanganyika and Balkash are missing in the ne_50m_lakes.shp

### ISSUE THREAD

**Issue by Anton21bis** [nvkelso/natural-earth-vector#422]
In the 4.1.0 version of ne_50m_lakes.shp Lake Tanganyika is missing. It does exist in the ne_110m_lakes.shp and in the ne_10m_lakes.shp.

**Comment by gzauhar** [comment]
In 4.1.0 lake Tanganyika is also missing from ne_50m_admin_0_countries_lakes.shp. It does exist in ne_10m_admin_0_countries_lakes.shp and ne_110m_admin_0_countries_lakes.shp.

**Comment by MrGawsome** [comment]
I can confirm that Lake Tanganyiki is missing on both the ne_50m_lakes and ne_50m_admin_0_countries shapefiles. ne_id 1159113185 needs to be added to the ne_50m_lakes shapefile with less detail than the 10m version and more detail than the 110m version. The lake's surrounding countries need to be edited to account for the lake shape on the ne_50m_admin_0_countries shapefile as well. Specifically, the countries of Burindi (ne_id 1159320387), Tanzania (ne_id 1159321337), Zambia (ne_id 1159321439), and the Democatic Republic of Congo (ne_id 1159320513) should be edited to exclude this lake's geometry. See below for screenshots of the missing data:

Missing in the ne_50m_lakes shapefile:
![image](https://user-images.githubusercontent.com/78829897/111395408-08ff1900-867a-11eb-92f6-4d81fef3bb75.png)

Missing in the ne_50m_admin_0_countries shapefile:
![image](https://user-images.githubusercontent.com/78829897/111395476-26cc7e00-867a-11eb-98b1-c601251283e9.png)

**Comment by MrGawsome** [comment]
I also confirmed that the lake is present on the 1:10 and 1:110 shapefiles for both the ne_lakes and admin_0_countries shapefiles. Only the 1:50m has the missing data.

**Comment by nvkelso** [comment]
I agree with this proposed change.

Once this lake is added to the 50m lakes theme, there is a Makefile target to generate the ne_50m_admin_0_countries_lakes theme by erasing the big lakes from the basic 50m countries file automatically: 

> make build_b3_ne_50m_admin_0_countries

https://github.com/nvkelso/natural-earth-vector/blob/master/Makefile#L503-L514

**Comment by nvkelso** [comment]
Hmm, history shows these lakes (and more) being included prior to v4. 

> git checkout 19eaa6b2956d762b40530cd4acaa70590e158b4c -- /Users/nvkelso/git-repos/natural-earth-vector/50m_physical/ne_50m_lakes.{shp,shx,dbf}

See also from history:

```
commit 8478836e2cbae0399e9fa607af543e8f2ff5d848
Author: Nathaniel Kelso <nvkelso@gmail.com>
Date:   Sun Apr 15 19:21:48 2018 -0700

    10m, 50m, 110m lakes wikidata

commit 19eaa6b2956d762b40530cd4acaa70590e158b4c
Author: Nathaniel Kelso <nvkelso@gmail.com>
Date:   Sun Oct 1 18:32:08 2017 -0700

    more min_zoom, split off () names to name_alt and add name_en for rivers
```

I've attached a ZIP of that missing content from 19eaa6b2956d762b40530cd4acaa70590e158b4c:

- [ne_50m_lakes_with_missing_features.zip](https://github.com/nvkelso/natural-earth-vector/files/6153784/ne_50m_lakes_with_missing_features.zip)

For the features already present in v5.0-pre (master), we need to add back the missing features from this earlier file. This will backfill these missing lakes (and many more). But the new features won't have all the wikidataid and name localizations so that'll need to be run again.

Then the Makefile target for `intermediate/ne_50m_lakes_big.shp` will need to change so only the "big" lakes are exported not all the ~130 new smaller lakes, too.

- https://github.com/nvkelso/natural-earth-vector/blob/master/Makefile#L497-L501

Looks like the filter should be something like **min_zoom** <= `4.7`?

More like the filter for the 10m big lakes:

- https://github.com/nvkelso/natural-earth-vector/blob/master/Makefile#L406

/cc @ImreSamu as something we did way back in 2017 and need to repeat again had problems last time. 🤷‍♂️

**Comment by ImreSamu** [comment]
@nvkelso :
my understanding : 
I need to generate a wikidata_id proposals  for the missing Lakes  -->  `ne_50m_lakes_with_missing_features.zip` ( 405 lakes )
   * please create a "new issue"   about this ( for me  )
   * please add/generate a new "ne_id" value.  (  lot of missing names)
   * probably in a next few weeks .. I can create a first result   ( ~ the first iterations  )

**Comment by nvkelso** [comment]
The **red** lakes are missing (but restorable via https://github.com/nvkelso/natural-earth-vector/commit/19eaa6b2956d762b40530cd4acaa70590e158b4c), the **blue** are current in v4 and v5-pre.

![image](https://user-images.githubusercontent.com/853051/117611208-f05e2d00-b117-11eb-992b-48eb86d0edea.png)

**Comment by nvkelso** [comment]
Select all "red" lakes that don't contain a centroid from the blue lakes. This results in 137 features (excluding the new Aral Sea changes by chance), but includes Lop Nur, so removing that manually leaves us 136 lakes to add back.

![image](https://user-images.githubusercontent.com/853051/117612053-69aa4f80-b119-11eb-88c1-ecb05b6a767b.png)

**Comment by nvkelso** [comment]
Lake Tanganyika is back:

![image](https://user-images.githubusercontent.com/853051/117719435-3e177b80-b192-11eb-94eb-11c2796544c2.png)
