### ISSUE TITLE
10m lakes: Lynx Lake & Whitefish Lake

### ISSUE THREAD

**Issue by elliotap** [nvkelso/natural-earth-vector#425]
10m lakes feature 1159108899 represents two separate lakes in Canada, Whitefish Lake and Lynx Lake. Currently, it is drawn as a single polygon named Lynx Lake. Requesting that geometries for Whitefish Lake and Lynx Lake be separated and Whitefish Lake be named.

References:
Northwest Territories Tourism Map: https://spectacularnwt.com/sites/default/files/2019-04/nwtt-map-foldout.pdf
Quaternary Science Reviews (see fig. 2): https://www.sciencedirect.com/science/article/pii/S0277379116307235#fig2
Wikipedia: 
Lynx Lake: https://en.wikipedia.org/wiki/Lynx_Lake_(Northwest_Territories)
Whitefish Lake: no page
Geonames: https://www.geonames.org/6180400/whitefish-lake.html

**Comment by nvkelso** [comment]
For **ne_id** = `1159108899`, I agree that feature should get _smaller_ (A in annotation below) so it's just the southern portion. 

A large portion of the original shape to the north (B) should be retained as a new feature (generate a new **ne_id** from https://www.brooklynintegers.com/create/) and with **name** = `Whitefish Lake`, and it should get a new **wikidata_id** (please research) so it picks up name translations.  The small lake to the north of there has **min_zoom**  of 6.7 with a **min_label** of 7.7. The Lynx Lake has 5.7 and 6.7. Other nearby lakes (in the North American suppliment theme) have 6.0 and 7.0. I'd use 6.0 and 7.0 for the new Whitefish Lake feature, which should also have **featurecla** of `Lake`, and **name_abbr** of `Whitefish L.`.

The new gap (c) between the lakes needs a new feature in the 10m rivers theme. Maybe it's already present as `Lake Centerline`? If so clip it and change the **featurecla** to `River` and investigate what the name might be and set that too. (Note the research in a comment here in this issue).

Also ensure that lake centerlines exist for D, E, and F – and that E and F converge as a wishbone towards the outflow drain within the polygon (see other examples browsing around in the file).

I don't think this feature exists in the 1:50m lakes file, but double check that. Either way it's probably too generalized at that scale to have different lakes here, so I'd leave it alone in either case.

![image](https://user-images.githubusercontent.com/853051/109751312-0fc66000-7b93-11eb-98d7-c951da4d3d85.png)

**Comment by MrGawsome** [comment]
Hi Nathaniel,

Thank you so much for your comments, they help a lot! I did some follow-up research and had some questions I wanted to run by you before moving forward with these edits. 

1. For Whitefish Lake, I propose using the following Wikidata link after reviewing over 251 possible Wikidata search results: https://www.wikidata.org/wiki/Q22610852. An English wikipedia page doesn’t exist for Whitefish Lake (see https://en.wikipedia.org/wiki/Whitefish_Lake_(Northwest_Territories)) and the closest Wikidata page besides the one suggested above is https://www.wikidata.org/wiki/Q1494317. So after considering these results, I think using Wikidata Q22610852 is the way to go here. What do you think?

2. For the lake centerlines, I am conflicted on how to proceed. It seems that either we can add the name “Thelon River” to all of the lake centerlines or have them added with no name. The lake centerlines exist in the ne_10m_rivers_north_america shapefile as unnamed rivers but don’t exist in the ne_10m_rivers_lake_centerlines shapefile. In the latter shapefile, “Thelon River” connects to the SE portion of Lynx Lake but doesn’t continue into the lake. 

I’ve done research into Thelon River and it seems like most maps and articles suggest that the river issues from Lynx Lake, which is what we have in the ne_10m_rivers_lake_centerlines shapefile. However, one of the main sources of the river describes the river’s source as “near Whitefish lake,” and wikipedia and OSM show the river stemming from Whitefish Lake as well. What would you prefer we do here, adding the name “Thelon River” to the lake center lines or having them be unnamed? 

See the below sources for more information: 

Sources showing Lynx Lake as Thelon River’s source: 
    - Natural Resources Canada (both of Northwest Territories and Nunavut pages): http://www4.rncan.gc.ca/search-place-names/unique/LAXWD and http://www4.rncan.gc.ca/search-place-names/unique.php?id=OAUJW&output=xml
    - The Canadian Encyclopedia: https://www.thecanadianencyclopedia.ca/en/article/thelon-river
    - University of Waterloo: https://uwaterloo.ca/nature-leisure-community-research-group/picturing-thelon-natures-ethics-and-travel-within-arctic

Sources suggesting Whitefish Lake as Thelon River’s source: 
    - Main source that suggests Whitefish Lake as the river's source (this source is referenced in many sources online, including in some of the above sources). See the text on both https://chrs.ca/en/rivers/thelon-river and https://apca.maps.arcgis.com/apps/MapSeries/index.html?appid=64fc674875f6473c8940048f2a05d3d9
    - Wikipedia: https://en.wikipedia.org/wiki/Thelon_River
    - OSM: https://www.openstreetmap.org/way/659968126

3. Whitefish Lake and Lynx Lake don’t exist in the 1:50m lakes file as expected. However, Thelon River exists (not as lake centerlines) in the ne_50m_rivers_lake_centerlines file. If we add Thelon River as lake centerlines for Whitefish Lake and Lynx Lake in the 1:10m lakes centerlines/rivers file, would we need to expand the river geometry in this 1:50m rivers file as well? Or is it good enough to leave it as is? 

4. Lastly, I’ve noticed that a lot of the rivers in the ne_10m_rivers_north_america shapefile are missing in the ne_10m_rivers_lake_centerlines shapefile and vice versa. I assume this is expected since together they show the larger watershed systems and connect with each other?

**Comment by nvkelso** [comment]
1. Agree on using `Q22610852` for **wikidata_id** for new "B" Whitefish Lake. The position matches. Someday there will be useful labels there, no worries in the time being.
2. No action on names – simplest to leave the NULL names for now. Thanks for all the research! Sorry, I didn't realize these were in the North American supplemental rivers – there's a lower bar on those ... lots of NULL names already.
3. Eh, leave 1:50m file alone then.
4. The supplemental rivers files are supposed to _augment_ but not _duplicate_ content in the basic theme. If you see duplicates that's a problem.

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/507.
