### ISSUE TITLE
Website certificate expired in October 2020

### ISSUE THREAD

**Issue by carderne** [nvkelso/natural-earth-vector#443]
Firefox and Chrome reporting expired certificate.

> This server could not prove that it is www.naturalearthdata.com; its security certificate expired 71 days ago. ...

**Comment by nvkelso** [comment]
Having a look...

**Comment by nvkelso** [comment]
@meijer3 commented over in https://github.com/nvkelso/natural-earth-vector/issues/416#issuecomment-742539668

![image](https://user-images.githubusercontent.com/45625341/101781544-3e82ec00-3af8-11eb-8b1f-6bb86d2c529b.png)

I cannot reach the website. I doubt that the end date is real, because it worked after this expired date.

**Comment by nvkelso** [comment]
I see the certificate expiring in 2021... but I did fix one other issue.

@meijer3 @carderne @larksk can you try again, please?

**Comment by carderne** [comment]
Good for me.

**Comment by nvkelso** [comment]
Woot!

**Comment by nvkelso** [comment]
Useful tool to debug SSL issues:

- https://www.sslshopper.com/ssl-checker.html#hostname=naturalearthdata.com
