### ISSUE TITLE
Wielkie Jeziora Mazurskie - 10m has poor tracing

### ISSUE THREAD

**Issue by matkoniecz** [nvkelso/natural-earth-vector#488]
Obviously, at 10m scale full details should not be expected.

But it seems to me that https://www.openstreetmap.org/#map=10/53.8857/21.5195 tracing can be improved to better match actual geometry and to provide better topology

Background: basically real data

Red outline: 10m_lakes dataset

![screen02](https://user-images.githubusercontent.com/899988/110101229-98b3e600-7da3-11eb-8408-db8afe951eda.png)

**Comment by nvkelso** [comment]
Is there a particular zoom 7 problem you’re trying to solve? Theses polygons were simplified algorithmically a while ago so I’m sure they could use some improvement.

But it is typical to simplify and exaggerate features during scale generalization. Otherwise a lake polygon looks like a line when it’s zoomed out.

**Comment by matkoniecz** [comment]
> Is there a particular zoom 7 problem you’re trying to solve?

Right now I am looking for dataset for rivers/lakes that would allow to make map of Europe for laser cutting on 45cm x 75cm piece of wood.

Simplifying OSM data is obnoxious, so I tried 10m Natural Earth dataset but it seems to rough - but I least wanted to report cases where geometry seemed clearly problematic.

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/492.
