### ISSUE TITLE
Unified Deep Water System of European Russia Fixes for 10m and 50m

### ISSUE THREAD

**Issue by MrGawsome** [nvkelso/natural-earth-vector#500]
The Unified Deep Water System of European Russia is a network of rivers, lakes, and canals that connect 4 large seas of Europe and Asia — the Black Sea, Caspian Sea, White Sea, and Baltic Sea — with various cities, including Moscow. Parts of this water system are missing, while other parts have inconsistent zoom levels or are located in the Europe supplemental rivers shapefile rather than the main 10m rivers shapefile. These issues were discovered from #340 and #14. Below is a proposal to fix these issues. 

Below is an image of an attached shapefile I made that displays the current rivers and lake centerlines that are part of this water system. In red are the water segments that are part of the ne_10m_rivers_europe shapefile and in blue are the rivers and centerlines that are part of the ne_10m_rivers_lake_centerlines shapefile. I propose we use a 4.7 zoom level for all parts of this system except for the Volga River, which can remain at z3, and 2 minor rivers of the system in the northeast, which can be changed to z6 instead of z4.7. In the shapefile you will find each NE segment with a proposed zoom level, notes on why that zoom level is proposed, and what file the water segment came from.

[chris_10m_russia_rivers_system.zip](https://github.com/nvkelso/natural-earth-vector/files/6193307/chris_10m_russia_rivers_system.zip)

![russia_water_system](https://user-images.githubusercontent.com/78829897/112222811-4584c480-8be6-11eb-9156-5a59a7f5708c.png)

Below are a collection of 5 screenshots of issues and the proposals to fix them. 

1) NE is missing a critical canal that connects the Volga River with the Don River, which in turn connects the Black Sea with the Caspian Sea and beyond. I propose we call this water segment the Volga-Don Canal based upon the below sources. We can use Wikidata id Q827505 to update the names. This canal’s location is at 48.55938493, 44.16050183.

Volga-Don Canal name sources:
Volgograd State University: https://volgaland.volsu.ru/en/object/13
Russian Presidential Library: https://www.prlib.ru/en/history/619278
Russian Port News: https://en.portnews.ru/news/287235/
Wiki: https://en.wikipedia.org/wiki/Volga%E2%80%93Don_Canal
Wikidata: https://www.wikidata.org/wiki/Q827505
OSM: https://www.openstreetmap.org/relation/2162772

![Missing_river_volga_Tsimlyansk_Reservoir](https://user-images.githubusercontent.com/78829897/112222869-5b928500-8be6-11eb-8c25-b6627854e34a.png)

2) NE is also missing the Moscal Canal, which connects Moscow to this water system. See the below sources to support this name. We can use Wikidata id Q741351 to update the names. This canal’s location is at 56.38504912, 37.50289654.

Missing Moscow Canal sources:
Inland Waterways International, which uses a great map: https://inlandwaterwaysinternational.org/blog/canals-through-the-eus-eastern-border/
Above map link: http://blog.inlandwaterwaysinternational.org/wp-content/uploads/2012/05/parisMoscowLarge.jpg
Nizhny Novgorodv website: http://www.smp.sci-nnov.ru/timetable.html
Euro River Cruises: http://eurorivercruises.com/UNI/Imperial%20Waterways%20of%20Russia.html
Wiki: https://en.wikipedia.org/wiki/Moscow_Canal
Wikidata: https://www.wikidata.org/wiki/Q741351
Main OSM relation for the canal: https://www.openstreetmap.org/relation/1731767

![Moscow_Canal](https://user-images.githubusercontent.com/78829897/112222907-66e5b080-8be6-11eb-9640-7381b0f2b766.png)

3) NE is missing a river connection to Lake Beloye at 60.43955173, 37.09101948. I suggest to remove the portion of the ne_id 1159112613 that goes east since it doesn’t seem to follow imagery and instead extend this river to the lake. See the below screenshot:

<img width="1917" alt="Missing_Supp_Connecction" src="https://user-images.githubusercontent.com/78829897/112222966-7c5ada80-8be6-11eb-9b9e-631c94b7c5d5.png">

4) A river and lake centerline seem to be slightly inaccurate according to imagery around 60.95931315, 36.00854113. I suggest to remove the small lake centerline of ne_id 1159123043 and to modify ne_id 1159112613 to extend into the lake at 61.09842285, 36.28279542. See the below screenshot:

![Lake_Onega_Centerlines](https://user-images.githubusercontent.com/78829897/112223014-8a106000-8be6-11eb-9efc-3d99cb59f1e0.png)

5) Another issue is where a false positive seems to exist according to imagery. The end of river ne_id 1159127815 finishes more north than it should following a railway path. The river shouldn’t continue north like in the below screenshot. Instead, the river should end at the coastline intersection at 64.55600936, 34.74449324. See below:

<img width="1919" alt="White_Sea_Canal" src="https://user-images.githubusercontent.com/78829897/112223043-94caf500-8be6-11eb-91d2-abfd9b232649.png">

**Comment by MrGawsome** [comment]
I recommend to add the NE segments from the ne_10m_rivers_europe shapefile to the ne_50m_rivers_lake_centerlines shapefile as well. We can also have all the fixes and zoom level changes for the 50m file as illustrated above.

**Comment by nvkelso** [comment]
I agree with the above, except for this one detail:

> NE is missing a river connection to Lake Beloye at 60.43955173, 37.09101948. I suggest to remove the portion of the ne_id 1159112613 that goes east since it doesn’t seem to follow imagery and instead extend this river to the lake. See the below screenshot:

It might be true that the natural headwaters extends as shown, but as a minor stream versus the canal. If that's the case than we can modify the min_zoom of the portion you proposed to remove to be a later (bigger) value). You'd also need to modify the 50m theme since it often continues to the headwaters.

**Comment by Maxszik** [comment]
I'm excited and enthusiastic about seeing these improvements. I've been making some small proposals earlier about these things. May I just add my comments?

1  _NE is missing a critical canal that connects the Volga River with the Don River, which in turn connects the Black Sea with the Caspian Sea and beyond. I propose we call this water segment the Volga-Don Canal_ Totally correct and very much needed.

2 As above, very much needed.

3 _NE is missing a river connection to Lake Beloye at 60.43955173, 37.09101948. I suggest to remove the portion of the ne_id 1159112613 that goes east since it doesn’t seem to follow imagery and instead extend this river to the lake_ True, correct.

_I suggest to remove the portion of the ne_id 1159112613 that goes east since it doesn’t seem to follow imagery_ This eastern part is a real river but not navigable and thus not very important, yes.

About the waterway between Lake Onega and the Rybinsk Reservoir. From north to south it goes like this: 

- The Vytegra River
- The Volga-Baltic Canal - sometimes called Volgo-Baltic Canal (man-made)
- The Kovzha River
- The White Lake - Beloe Lake/Ozera
- The Sheksna River (including in parts the Sheksna Reservoir)
- Ends at Cherepovets

The above parts together form the Volga-Baltic Waterway which stretches all the way between St Petersburg and Cherepovets. So the Volga-Baltic Canal is a small part of the overall Volga-Baltic Waterway. The parts before the above mentioned beginning at Lake Onega are the Svir River, Lake Ladoga, and the Neva River leading to St Petersburg and the Gulf of Finland.

4 _A river and lake centerline seem to be slightly inaccurate according to imagery around..._ This seems to be in parts the old Onega Canal. It still exists and it's still there, but it has zero importance economical importance and is not available for commercial shipping. Nice for canoeing.

5 _Another issue is where a false positive seems to exist according to imagery_ True, correct.

A few other observations:

- The Kama River is navigable not to Perm only, but beyond to Solikamsk.
- A part of the Unified Deep Water System of European Russia is the Belaya River, a tributary of the Kama, from the Kama to Ufa.
- The Vyatka River, a tributary of the Volga, is navigable up to Kirov
- The Volkhov River is navigable down from Lake Ladoga to Veliky Novgorod

As for all the suggestions about zoom levels and such, I myself agree very much.

I'm an enthusiastic hobbyist mapper lacking any professional skills, pls forgive me if I have misunderstood what this issue is really about. I would love to help and I'm watching this space, pls let me know if I can be of any help. I've been sailing these waterways for fifteen yrs.

[Here's a map](https://gist.github.com/Maxszik/2ef6a8844e4fc5f312cd290d4812084c) I made many years ago using Natural Earth, and hacking and patching the Sheksna, Moscow Canal, White Sea Canal and Volga-Don on my own.

**Comment by nvkelso** [comment]
Fixed via https://github.com/nvkelso/natural-earth-vector/pull/525.
