### ISSUE TITLE
Coast is boxy

### ISSUE THREAD

**Issue by Basil3ios** [nvkelso/natural-earth-vector#557]
Hello everbody
I am new to natural earth and I was wondering why my coast is so boxy?
![Screenshot (60)](https://user-images.githubusercontent.com/87417298/125595143-3f204f64-6df9-495d-a073-015485d774da.png)

I have downloaded the esri arcreader and hoped that it would wotk now, but that doesn't seem to be the case.
Does anybody know why this happens and how to fix it?
Thanks in advance

**Comment by elliotap** [comment]
you have only loaded a single raster file here. this is expected behavior. natural earth has many files, both raster and vector, that can be used in all sorts of permutations - if you are a student, file an issue against my fork [here](https://github.com/elliotap/natural-earth-vector), and tell me a little bit about your studies, and I will take the time to explain via comments what you're seeing in this case, and how you can work with the data. you might also close this issue.

please note, however: github issues are not a great place to ask beginner questions. projects on here are largely maintained by volunteers, and issues that get addressed largely concern underlying issues with code or data. you are more likely to find an answer to functional questions if you look to textbooks, peers, subject matter blogs and forums, and social tech sites like stack exchange/stack overflow.

**Comment by nvkelso** [comment]
As @elliotap said this raster theme is meant to be combined with vector water overlay, either from NE or bring your own (BYO). Other versions of raster theme have the NE water pre-composited.
