### ISSUE TITLE
French Guyana is missing from South America + suggested solution

### ISSUE THREAD

**Issue by SietzeN** [nvkelso/natural-earth-vector#677]
Hello,

I found that French Guyana is missing from the dataset, and also suggest a way to solve it. 

Politically, French Guyana is part of France: https://en.wikipedia.org/wiki/French_Guiana
france <- rnaturalearth::ne_countries(country = "France", returnclass = "sf", scale = "medium")
tmap::tm_shape(france) + tmap::tm_polygons()

It is located on the South American continent, but when you download the entire continent of South America, there is a hole where French Guyana should be
sa <- rnaturalearth::ne_countries(continent = "South America", returnclass = "sf", scale = "medium")
tmap::tm_shape(sa) + tmap::tm_polygons()

Perhaps French Guyana could be added as geounit within South America?

Thanks!

**Comment by MLWorley** [comment]
Further comment (just adding some details to previous commenter's issue).

I can see that French Guiana does appear in ne_10m_admin_0_countries as part of France (ne_id = 1159320637), so in that data set it is using iso_A2 = 'FR' and all the information for France instead of any separate information for French Guiana (which would've had ISO_A2='GF' if it had had its own entry). In the ne_10m_admin_0_countries dataset, the entry for France which includes French Guiana has CONTINENT='Europe'. The WOE_NOTE field in ne_10m_admin_0_countries for France says 'Includes only Metropolitan France (including Corsica).' (I realize that that only applies to WOE information but mention it in case the WOE tagging has some effect I'm unaware of in filtering.)

In ne_10m_admin_0_countries, Martinique and Guadeloupe are similarly being included in the entry for France rather than using their alternate ISO 3166 country codes (MQ, GP), so they would similarly appear as part of Europe rather than Latin America and the Caribbean.

In ne_10m_admin_0_countries, French Polynesia avoids having a similar problem to the French Guiana issue by having its own entry and using iso_A2='PF' rather than using the alternate ISO 3166 representation as part of France itself.

**Comment by SietzeN** [comment]
Yes, thanks for the addition. Perhaps the best solution would be to split the polygon and giving each of the their own entry.

**Comment by MLWorley** [comment]
Some additional info for various French overseas departments which Natural Earth is currently treating as part of France (at least in ne_10m_admin_0_countries and ne_10m_admin_1_states_provinces). (Some of the other French overseas departments currently are treated differently in Natural Earth, however, see below.)

**Guadeloupe** (https://www.wikidata.org/wiki/Q17012)
- WOEID = 23424831
- For ISO 3166, has representations **ISO_A2='FR', ISO_3166_2='FR-GP'** but also **ISO_A2='GP'** in its own right.
- ne_id = 1159315647 in ne_10m_admin1_states_provinces, which currently shows it with ISO_A2='FR', ISO_3166_2='FR-GP'.
- ne_id = 1159320637 in ne_10m_admin0_countries (shown as part of France, so it is showing up as CONTINENT = 'Europe'). Actually it is in the Caribbean.


**Guyane Française** (French Guiana) (https://www.wikidata.org/wiki/Q3769)
- WOEID = 23424811
- For ISO 3166, has representations **ISO_A2='FR', ISO_3166_2='FR-GF'** but also ISO_A2='GF' in its own right
- Previous comment gives its ne_id values for ne_10m_admin0_countries (part of France, currently, and thus as part of Europe rather than South America) and ne_10m_admin1_states_provinces (again part of France rather than alternate representation with ISO_A2='GF')

**Martinique** (https://www.wikidata.org/wiki/Q17054)
- WOEID = 23424884
- For ISO 3166, has representations **ISO_A2='FR', ISO_3166_2='FR-MQ'** but also **ISO_A2='MQ'** in its own right
- ne_id = 1159311599 in ne_10m_admin1_states_provinces, which currently shows it with ISO_A2='FR', ISO_3166_2='FR-MQ'.
- ne_id = 1159320637 in ne_10m_admin0_countries (shown as part of France, so it is showing up as CONTINENT = 'Europe').

**Mayotte** (https://www.wikidata.org/wiki/Q17063)
- WOEID = 23424886
- For ISO 3166, has representations **ISO_A2='FR', ISO_3166_2='FR-YT'** but also **ISO_A2 = 'YT'** in its own right.
- ne_id = 1159315621 in ne_10m_admin1_states_provinces, which currently shows it with ISO_A2='FR', ISO_3166_2='FR-YT'.
- ne_id = 1159320637 in ne_10m_admin0_countries (shown as part of France, so it is showing up as CONTINENT = 'Europe'). Actually Mayotte is an island in the Mozambique Channel, so would more logically be part of Africa.

**La Reunion** (https://www.wikidata.org/wiki/Q17070)
- WOEID = 23424931
- For ISO 3166, has representations **ISO_A2='FR', ISO_3166_2='FR-RE'** but also **ISO_A2='RE'** in its own right
- ne_id = 1159315617 in ne_10m_admin1_states_provinces, which currently shows it with ISO_A2='FR', ISO_3166_2='FR-RE'.
- ne_id = 1159320637 in ne_10m_admin0_countries (shown as part of France, so it is showing up as CONTINENT = 'Europe').

The following French overseas collectivities currently are being treated as countries by Natural Earth, however
- Saint-Barthélemy, iso_A2='BL'
- Saint-Martin, iso_A2='MF'
- Saint-Pierre-et-Miquelon, iso_A2='PM'
- Nouvelle-Calédonie (New Caledonia), iso_A2 = 'NC'
- Polynésie française (French Polynesia), iso_A2='PF'
- Terres australes françaises, iso_A2='TF'
- Wallis-et-Futuna, iso_A2 = 'WF'

(The truly odd one out is Ile d'Clipperton, which has its own issue. It's currently represented in ne_10m_admin_1_states_provinces as a separate unit but not tagged as iso_A2='FR', iso_3166_2='FR-CP' nor as ISO_A2='CP'.)

**Comment by nvkelso** [comment]
Natural Earth treats the overseas regions of France the same as we treat the overseas states of the United States, as one with its metropolitan core in the countries theme. The map units offer the level of detail you seek.

**Comment by SietzeN** [comment]
Thanks for your reply.

You're right that French Guyana is politically part of France, but it is still located on the South American continent. Currently, selecting data for South America leaves a hole for French Guyana. I don't think this is desirable (see screenshot below, R code below).


![afbeelding](https://user-images.githubusercontent.com/29064687/157458975-ace5e2ab-bc53-44a2-9c10-3fd168202894.png)

sa <- rnaturalearth::ne_countries(continent = "South America", returnclass = "sf", scale = 110) 
tmap::tm_shape(sa) + tmap::tm_polygons()
