### ISSUE TITLE
Consistency of "de facto boundaries" policy breached, urgent!

### ISSUE THREAD

**Issue by devrand** [nvkelso/natural-earth-vector#810]
Currently "[de facto boundaries](https://www.naturalearthdata.com/about/disputed-boundaries-policy/)" policy in this project [is used ](https://twitter.com/dvrnd/status/1565687924800344064) only to support Russian colonial point of view on occupied Crimea (which by default shown as a part of Russia).
To apply official "de facto boundaries" in consistent manner (not only for Crimea but for other territories _de-facto controlled_ by Russia ) we need to add borders for this list of territories:

- South Ossetia ("breakaway" from Georgia, military and politically supported by Russia), 
- Abkhazia ("breakaway" from Georgia, military and politically supported by Russia), 
- Part of Donetsk region (occupied and controlled by Russia), 
- Part of Luhansk region (occupied and controlled by Russia), 
- Transnistria ("breakaway" from Moldovia, military and politically supported by Russia), 
- Artsakh ("breakaway" from Azerbaijan, aka Nagorno-Karabakh, military and politically supported by Russia)
- Parts of Zaporizhzhya, Kherson, Kharkiv regions currently occupied and **controlled** by Russia after 2022-02-24

Please, correct these inconsistencies immediately. 
Thank you very much, yours truly, 
MFA RF

**Comment by nvkelso** [comment]
Hello again! Thank you for your clear and consistent feedback, this time with an admirable dose of dark humor about the boundaries of Ukraine and Russia in the default Natural Earth point-of-view (which remains de facto). As stated before, I'm personally no fan of Putin or his aggressive and senseless war in Ukraine.

These and other disputed areas are already marked in Natural Earth, per prominently displayed written policy, in the admin polygons and boundary line themes.

If a country officially annexes a disputed territory like Crimea and it occupies it on the ground then yes it'll show up in Crimea's case as part of Russia for the default point-of-view, but not for most the per country points-of-view since most other countries don't recognize that situation.

If a country does not annex but meddles than it'll show as breakaway polygon and/or "dashed" line.

In the case of the other Ukrainian disputed areas, they are only recognized by Russia but not annexed, and/or in an active and fluid war zone. Thus the two breakaway republics are only shown as "countries" in the Russian point-of-view, but breakaways in default with the "solid" country line aligned on the Ukraine and Russia frontier before the war.

See also:

https://www.washingtonpost.com/world/2022/09/19/ukraine-russia-war-nuclear-plant-pugacheva/

**Comment by devrand** [comment]
It immediately follows from your explanation above, that your rule must be named as **"de-facto boundaries for areas annexed by Russia"**  

This will be much more precise, short, and honest definition than your long attempt to justify your support for Russia.

**Comment by breki** [comment]
> If a country officially annexes a disputed territory like Crimea and it occupies it on the ground then yes it'll show up in Crimea's case as part of Russia for the default point-of-view

Let me get this straight: you will mark the Zaporizhia oblast as belonging to Russia just because Putin decided to magically annex it, even though they don't even control its capital and only 2/3 of its territory is occupied? Should we then interpret this as saying the Ukrainians are then the occupying force of that Russian territory? Or will you do a daily update of new Russian borders based on how the frontline moves?

![image](https://user-images.githubusercontent.com/226863/192348107-e098f7fc-25e4-4404-9032-6fa7bcd1ec90.png)

**Comment by PeterNjeim** [comment]
@devrand Abusive language will not be tolerated. In this case you're falsely accusing someone having a political belief they already claimed they did not have.

Moving on, your claim is flatly false. An accurate map shows boundaries that a country "claims and controls". Both must be satisfied. This isn't a specific rule to any particular country.

Example: India and Pakistan have competing claims on parts of Kashmir. A de jure map of Pakistan would show all of Pakistan's claims. A de jure map of India would show all of India's claims. But what if we wanted a world map, with both India and Pakistan on it? A de jure world map would simply overlap their claims with a dotted line.

Why is de jure a bad map style? Because it respects unrealized claims.

A de facto map of Pakistan would show all of Pakistan's controlled claims. A de facto map of India would show all of India's controlled claims. A de facto world map with both India and Pakistan would show Pakistan's border end and India's border start where the line of control transitions. This is more accurate as it only respects realized claims.

The good thing about India and Pakistan is that borders aren't changing day-to-day as is the case with Russia and Ukraine. Before this point, Russia wasn't claiming the regions it just annexed, therefore only Ukraine, LPR, and DPR were claiming conflicting areas. Ukraine claimed all of Donetsk, yet only controlled part of it (and to slight you I will unnecessarily add that they didn't control its capital and had to move to a new one). Same with the DPR, as they were claiming all of Donetsk, yet only controlled part of it. So in a de facto map, an accurate map, a respectful map, there would be a border between the DPR and Ukraine, with no overlap. Now that Russia has annexed 4 regions, it simply changed its claims. Now it claims all of the 4 regions, yet just as in our previous examples, it only controls part of them. Same with Ukraine. It claims all of the 4 regions, yet only controls part of them. Therefore the de facto map must change, as the claims have changed.

**Comment by PeterNjeim** [comment]
@breki Simply put, since Russia has now annexed the regions, what they do control is de facto part of Russia, and what they don't control is de facto part of Ukraine. Your statements about "occupation" don't even relate to de facto boundaries whatsoever, keep that discussion away from here. South Ossetia and Abkhazia are different as Russia does not claim the territory for themselves, in fact Russia recognizes their sovereignty.

Daily updates would indeed be the only way to keep the map correct, and anytime it doesn't match what's on the battlefield, the map is indeed objectively incorrect. However, Wikipedia editors are going to be updating the map themselves regardless of what Natural Earth does, so it's not too important. Maybe once a week would be ok. This is a rare instance of an annexation happening during a fluid moment of war, as usually annexation occurs after control over the whole of the desired territory is attained.

**Comment by breki** [comment]
> @breki Simply put, since Russia has now annexed the regions, what they do control is de facto part of Russia, and what they don't control is de facto part of Ukraine. Your statements about "occupation" don't even relate to de facto boundaries whatsoever, keep that discussion away from here. 

I am talking to the people who are the original authors of Natural Earth and who made the decision to hide behind a "de facto" argument instead of making conscious editorial decisions about the map data that now a lot of people use as their source for maps, without knowing that they use the data that supports genocidal regimes' actions.
Who exactly are you?

> South Ossetia and Abkhazia are different as Russia does not claim the territory for themselves, in fact Russia recognizes their sovereignty.

Where did you read me mentioning South Ossetia and Abkhazia?

**Comment by webknjaz** [comment]
> @devrand Abusive language will not be tolerated. In this case you're falsely accusing someone having a political belief they already claimed they did not have.

This project straight up abuses the whole nation and enables the terrorists. This is in the same category racism and other forms of discrimination. I guess it's okay if the project author does this but not the abused party. Hello, double standards.
This policy is an absolute support of the ruscism and nothing else, no matter how the so-called "liberals" claim.
Actions speak louder than words.
And actions of this project are terrorist.

**Comment by MaxGraey** [comment]
> @devrand Abusive language will not be tolerated. In this case you're falsely accusing someone having a political belief they already claimed they did not have.

You know who else recognizes Crimea as Russia's? Dictator Lukashenko in the singular (not the people of Belarus, mind you!). And he did it relatively recently. Belarus is now completely dependent on Russia, moreover, it is a bridgehead for the Russian army, providing its airports. Missiles fly from there. So, even the totally dependent dictator Lukashenko recognized the Crimea as Russian only under pressure from Putin.

You are the only person who decided that his project would spit on all moral political and legal norms and come up with some very convenient wording. Well now you have to be consistent and include the other annexed areas.

You have a right and a wrong choice. But you will have to make it. Let's see what the right choice is for you!

**Comment by PeterNjeim** [comment]
> I am talking to the people who are the original authors of Natural Earth and who made the decision to hide behind a "de facto" argument

Again, abusive language will not be tolerated. You don't have evidence to use the word "hide" here. De facto status is quite literally the point of Natural Earth. If it wasn't, then what would the map look like? Would it follow US foreign policy (aka CIA World Factbook)? Then Sudan would control the Hala'ib triangle instead of Egypt, etc. Would it follow Chinese foreign policy? Then Taiwan wouldn't be a country on the map, etc. Natural Earth shows 209 sovereign states on its maps. No sovereign state on Earth recognizes 208 other states. It's not Natural Earth's job to look at the world through a single country's perspective, not Russia's, not China's, not anyone's. That's why their maps are so accurate, and are used in Wikipedia as a result :).

> instead of making conscious editorial decisions about the map data that now a lot of people use as their source for maps, without knowing that they use the data that supports genocidal regimes' actions.

This is a logical fallacy. It doesn't matter if someone says 2+2=4 and then Russia says 2+2=4, that has no impact on the motive of the first person claiming 2+2=4. In this case, you're claiming that since Russia says it's part of their territory, and Natural Earth is showing it as part of their territory, then Natural Earth must be doing it because it "supports" Russia. This is a [guilt by association](https://www.logicallyfallacious.com/logicalfallacies/Ad-Hominem-Guilt-by-Association) logical fallacy.

> Who exactly are you?

Again, abusive language will not be tolerated. The truth doesn't change depending on my identity. Something tells me you use social media, because your statements (along with the others here) seem to be very high in fallacies and very low in actual substance. I personally don't use social media so I'm not used to facing so many fallacies in a single message.

> Where did you read me mentioning South Ossetia and Abkhazia?

I didn't, I was replying to you before the other guy, and forgot to move this sentence there, sorry lol

**Comment by PeterNjeim** [comment]
> This project straight up abuses the whole nation and enables the terrorists.

False. Because I already countered this claim in my initial comment, I won't be repeating myself. GitHub is not social media, so please stop bringing social media tactics here. And again, abusive language will not be tolerated.

> This is in the same category racism and other forms of discrimination.

This false, abusive statement is a grave violation of the GitHub ToS. I will be reporting you on @nvkelso's behalf.

> I guess it's okay if the project author does this but not the abused party. Hello, double standards.

What does this even mean? Ukraine themselves claim that Russia is occupying parts of their territory. If I assume you mean Ukraine when you say "abused party" (remember that you're abusing the developer here, he's the abused party, Ukraine isn't a party to our conversation, nor is Russia nor any other country, as Natural Earth doesn't respect any country's foreign policy, which is the whole point of this project). What do you mean "double standards"? This project is specifically designed to use a single standard, not multiple. It goes like this: if a country claims land, nothing happens. If a country claims and controls land, it shows it. That's a singular standard. Therefore your statement is false. In fact, not showing Russia's territory as having its newly annexed regions (the parts which it controls) would be a double standard. You're promoting a double standard, not the other way around.

> This policy is an absolute support of the ruscism and nothing else, no matter how the so-called "liberals" claim.

All evidence points to the contrary. It points towards the upholding of a single standard as described earlier. I don't know what the "so-called 'liberals'" are, you're just making things up at this point. This isn't social media, this a code discussion forum, please stay on-topic.

> Actions speak louder than words.

I agree. Your actions are abusive.

> And actions of this project are terrorist.

Like I said in the message above, this is a guilt by association logical fallacy. You didn't demonstrate how Natural Earth supports terrorists, just that you perceieve them to be. Natural Earth has already explained why the map is the way it is, and how it quite literally does not "support" anyone, it literally does the opposite of "support".

**Comment by PeterNjeim** [comment]
> You know who else recognizes Crimea as Russia's? Dictator Lukashenko in the singular (not the people of Belarus, mind you!). And he did it relatively recently.

Again, guilt by association logical fallacy. Please stop bring social media tactics to this non-social media platform. Either say something of substance or do not respond at all.

> Belarus is now completely dependent on Russia, moreover, it is a bridgehead for the Russian army, providing its airports. Missiles fly from there. So, even the totally dependent dictator Lukashenko recognized the Crimea as Russian only under pressure from Putin.

Thanks for the history lesson :). Since you didn't give any citations or sources, one should take your statement with a grain of salt. Not sure how it's relevant to our conversation though...

> You are the only person who decided that his project would spit on all moral political and legal norms and come up with some very convenient wording.

No, I don't make Natural Earth and didn't decide anything. Not only that, but no one here is "spitting" on anything. Morality doesn't play into cartography, at all. Political "norms"? What? That refers to how members of a legislature act and the like, not a map. Legal "norms"? The law of Ukraine says the 4 newly annexed regions are Ukraine's. The law of Russia will soon claim that the 4 newly annexed regions are Russia's. That's what the law says. Again, just because a country claims land doesn't mean the map should show the land as theirs. Whether it's Russia claiming it, or even Ukraine for that matter. What matters is if they control land that they claim. "Very convenient wording"? Again, what? You take issue with the term de facto? Ok, let's use plain English then, it would mean "factual" in this context. Factually, most of Luhansk is under Russian sovereignty. Factually, all of Crimea is under Russian sovereignty, etc. Do you like that wording? I don't understand your argument at all. Your only issue is that he used some Latin words? Well since I translated it to English now you'll have no problem, right? Lol, we all know you'll just make something else up instead ;).

> Well now you have to be consistent and include the other annexed areas.

Exactly. When Russia officially ratifies the annexations (next week probably), I expect Natural Earth to start showing the annexed territories that are under Russia control as Russian territory proper.

> You have a right and a wrong choice. But you will have to make it. Let's see what the right choice is for you!

The right choice is not listening to logically fallacious people like yourself. There's a reason I left social media, and it was to avoid dealing with logical fallacies like yours. Unfortunately this GitHub issue seems to be attracting those from social media.

**Comment by PeterNjeim** [comment]
Now that I've explained everything, it doesn't seem like there's any counterarguments left. Here's a summary.

The facts:
- Natural Earth doesn't respect any country's foreign policy. Otherwise the map would be missing countries and have borders that don't match what's on the ground.
- Natural Earth's goal is to truthfully represent the borders. This means ignoring country's claims and instead focusing on what they control, as long as they claim it too. This is known as a single, truthful standard. Just because Ukraine is involved now doesn't change anything. The same standard is applied to Kashmir, to Palestine, Western Sahara, etc.
- Guilt by association is not an argument. Remember that Russia's map will include the entirety of the 4 annexed regions. Natural Earth won't do this, it'll only show what it controls, due to the single, truthful standard. India for example claims all of Kashmir, but Natural Earth shows Pakistan and China as controlling parts of Kashmir, since respecting India's claim is not the goal of Natural Earth, it's to show what India actually controls of their claim. Respecting Russia's claim and not what they control is not the goal of Natural Earth, otherwise the map would be wrong (as you agree).

I won't be responding further as the social media-esque aspect of this discussion is repulsive to me. I don't enjoy reading a logical fallacy every sentence.

**Comment by MaxGraey** [comment]
> Guilt by association is not an argument. Remember that Russia's map will include the entirety of the 4 annexed regions. Natural Earth won't do this, it'll only show what it controls, due to the single, truthful standard. India for example claims all of Kashmir, but Natural Earth shows Pakistan and China as controlling parts of Kashmir, since respecting India's claim is not the goal of Natural Earth, it's to show what India actually controls of their claim. Respecting Russia's claim and not what they control is not the goal of Natural Earth, otherwise the map would be wrong.

Every major city has a Chinatown. Often there live Chinese immigrants who do not know the local language. They have their own rules and often their own laws. There are local gangs who control the area better than the police.  By your logic, this neighborhood would belong to China if the Chinese declared it their territory.

You still do not understand that by your rhetoric you are creating a precedent, first, and second, you are helping to legitimize subsequent annexations. Natural Earth is used by many publications that cover politics. Moreover, you support the right of Brute Power instead of the right of Law. You are essentially playing into the hands of totalitarian regimes

**Comment by webknjaz** [comment]
> Morality doesn't play into cartography, at all. 

It's interesting how the westsplainers can make excuses for immoral behavior if it doesn't fit their world views. The current behavior indulges propaganda on the scale because most of the users don't know that they can change the PoV, which is why such defaults are harmful and work for the terrorists.
Having a terrorist-by-default setting is not helpful.

> Lol, we all know you'll just make something else up instead

🤡🤡🤡 Like you do? Telling Ukrainians that they don't know what's happening at their home is not a fallacy because...?

**Comment by nvkelso** [comment]
No, Natural Earth won't immediately update. 

As you know, this is an active war zone with a line of control that shift substantially day to day (unlike earlier in the Crimea peninsula). Russia now claims sovereignty over the 4 additional Ukrainian regions (plus the 2 original in Crimea), so any future update would likely switch the solid line admin-0 to a dashed along the old UKR-RUS eastern admin-0 frontier in the default view, and switch those partial/whole regions to a claim area (with updates in the POV as appropriate). As you point out Russia doesn't actually control the ground in most the UKR regions it now asserts claim to -- making drawing the western edge of a polygon problematic since there is no fixed location. Natural Earth is both a volunteer project and we generally track larger actions and statements about intent and sustained holding of territory (note the 3 years before making the Crimea change to the default shapes).

A walk down memory lane:

The project's CHANGELOG lists important changes in the data project.

- v4.0.0 (Oct 2017) - Three years after Russia annexed Crimea, Natural Earth updated to reflect that change in the de facto situation with appropriate disrupted territory demarcations. To this day, Russia continues to control the Crimea peninsula territory, and has incorporated the two states there into its federal system, including a billion dollar transport network, distinguishing it from several of the other proxy territory wars it's fought, say in Georgia. 

- v5.0.0 (Dec 2021) -  Added point-of-view tagging to support several dozen popular (or unpopular as the case may be!) worldviews for country boundaries. This reflects a country's views of itself, and of 100 other disputed boundaries around the world. It's paired with name localization. This includes a Ukrainian POV because of the significance of the Russia <> Ukraine conflicts. Ukrainian name localization support was also added.

- v5.0.1 (March 2022) - point-of-view updates to reflect the start of Ukraine <> Russia war and changing global attitudes around the conflict. Net result: more countries side with Ukraine's view, only few with Russia's. 

- v5.1.x (May 2022) - refinement to the POV, including for Ukraine, based on continued evolution of global attitudes, including a new TLC point-of-view config making it easier to remix.

In the lead up to the Ukraine <> Russia war, and during development of the v5.0.0 release there was discussion in Github Issue #391, where I heard and responded to feedback about Ukraine. 

To be clear: I am not a fan of Putin's Russia. I personally think what he is doing in Ukraine is horrible and against my own values. I have given money to a Ukrainian refugee organization. But to help understand and resolve that conflict there does need to be an objective de facto acknowledgement of who controls and asserts what about the territory on the ground – not a singular partisan viewpoint. Natural Earth includes many viewpoints now, and you can choose one and even diff between them.

**Comment by monfera** [comment]
> GitHub is not social media

Says the person who gave a 👍 to all six of _**his own**_ comments in this issue alone

**Comment by PeterNjeim** [comment]
I randomly decided to check back here to see if anyone replied to me in #​812 but it seems no one has. Then I looked here and I saw @monfera, the guy who I wrote my essay to! I'm surprised to see you here, considering you never responded to my comment to you. Luckily, 0 people responded to me, meaning there was no counter argument that anyone could muster. All they could do was dislike, because their social media habits make them think it does something. I'm not saying you're like that, of course, you did make a valuable comment to me earlier. I was wondering, just for personal reasons, do you actually disagree with the [essay I wrote to you](https://github.com/nvkelso/natural-earth-vector/issues/812#issuecomment-1265871415)? I spent a lot of time writing it, making sure my arguments made sense and explained simply. I was disappointed that not a single person replied to it (well, happy because now I know I'm right, but sad because I like discussing things). What are your thoughts on it? Do you think marking disputed territories by their name and not by who controls them is better? (Referring to all of Kashmir as "Kashmir (disputed)", etc.?). I'd like to hear whatever you have to say about it, and if you don't want to talk about it that's okay too :)
