### ISSUE TITLE
Malta's UN membership status incorrectly described on https://www.naturalearthdata.com/about/disputed-boundaries-policy/

### ISSUE THREAD

**Issue by theohonohan** [nvkelso/natural-earth-vector#880]
The page on Natural Earth's [disputed boundaries policy](https://www.naturalearthdata.com/about/disputed-boundaries-policy/) currently describes Malta as one of several "non-member “observers” to the UN".

This is incorrect. Malta is a full member of the UN, and has been since 1964.

**Comment by iebb** [comment]
I think it might be referencing to the Sovereign Military Order of Malta, a UNGA non-state observer, unrelated to the present country of Malta.

[SMOM was granted observer status in 1994 with A/RES/48/265](https://digitallibrary.un.org/record/161740?ln=fr)

**Comment by nvkelso** [comment]
Thanks for the report! I've updated the text to remove reference to Malta. 

The situation is a little confusing as @iebb points out, but I agree here it should be the Country of Malta not the Sovereign Military Order of Malta and since Malta the country has been the UN member [since 1964](https://www.un.org/en/about-us/member-states#gotoM) then the reference should be removed and the two remaining countries kept.

The change should be live on the site now.
