### ISSUE TITLE
cartopy: when reading country polygons, 22 countries come without ISO_A2 and ISO_A3 label 

### ISSUE THREAD

**Issue by pietervanderhijden** [nvkelso/natural-earth-vector#913]
When generating country polygons from cartopy with:

shapename = 'admin_0_countries'
countries_shp = shpreader.natural_earth(resolution='10m', category='cultural', name=shapename)

there are 22 countries without ISO_A2 and ISO_A3 labels (which I use as unique country key):

-99 -99 Akrotiri Sovereign Base Area
-99 -99 Ashmore and Cartier Islands
-99 -99 Bajo Nuevo Bank (Petrel Is.)
-99 -99 Baykonur Cosmodrome
-99 -99 Bir Tawil
-99 -99 Brazilian Island
-99 -99 Clipperton Island
-99 -99 Coral Sea Islands
-99 -99 Cyprus No Mans Area
-99 -99 Dhekelia Sovereign Base Area
-99 -99 France
-99 -99 Indian Ocean Territories
-99 -99 Kosovo
-99 -99 Northern Cyprus
-99 -99 Norway
-99 -99 Scarborough Reef
-99 -99 Serranilla Bank
-99 -99 Siachen Glacier
-99 -99 Somaliland
-99 -99 Southern Patagonian Ice Field
-99 -99 Spratly Islands
-99 -99 US Naval Base Guantanamo Bay

Please, advice.

**Comment by nvkelso** [comment]
Most of those places don't have an ISO code because ISO doesn't have codes for them (they are also generally very small places and are often also disputed territories). 

Several of them do have ISO codes like `France` and `Norway`... just not at the admin_0 level you're looking at. Because of the slight miss-match, the exact equivalencies are listed in the appropriate level (different downloads), and for ease of use there's an `ISO_A3_EH` (as in, "eh, not a perfect match but could work for you with caveats" fuzzy matches). So there will be some "use with your own caution" involved, but the `ISO_A3_EH` should work better for you.
